Adding algorithm logging. Alg now symmetric with respect to I1, I2.
lsst-ts/ts_wep_older pull request #152
Opened 2022-09-28 19:44 UTC by jfcrenshaw

### Algorithm Log:
This PR adds internal logging to the algorithm, which you can see in action in [this notebook](https://gist.github.com/jfcrenshaw/751848194c27a1e79b6f51d20193a48c).

There is logging for the outer and inner loops of the algorithm, including the initial images, the compensated images, the masks, the estimated zernikes and wavefronts, and the reason for terminating the outer loop.

You can set the `debugLevel` at which each object is logged. I have set everything to be logged when `debugLevel>=1`, but we can change this if people want.

The algorithm log is not saved in the butler when running the pipeline tasks. I will open a separate ticket aimed at getting the log integrated in the pipeline tasks.

### Other changes:

In the process of setting up this logging, I restored the symmetry of the algorithm with respect to `I1` and `I2`. This required two things:

#### 1. Simplifying rotations of the masks and images

After this update, masks match the orientations of the original images (i.e. the orientation of the extrafocal and intrafocal masks are different by 180 deg, because the orientation of the corresponding images are different by 180 deg).

The orientation of the extrafocal image is made to match the orientation of the intrafocal image during image compensation, which happens while running the algorithm. The algorithm then applies masks to the compensated images. For this reason, when the algorithm creates the masks, it calls `makeMask(..., compensated=True)`. This causes the masks to match the orientation of the compensated images (i.e. the extrafocal mask is now rotated 180 deg to match the orientation of the compensated extrafocal image).

#### 2. Simplified and fixed the calculation of `I0` and `dI`

The algorithm requires the calculation of the mean image, `I0`, and the difference image, `dI`. The "exp" and "fft" algorithms were both doing this, using separate bits of code. I removed the code duplication, so both algorithm modes are using the same method to calculate these images (i.e. `Algorithm._getdIandI0`).

The sign of the difference image, `dI`, is sensitive to which image is extrafocal and which image is intrafocal. I fixed this by introducing an additional minus sign whenever `I2` is extrafocal.

2022-09-28 22:00 UTC, suberlak requested changes
Since it's a major change to one of the core elements of `ts_wep`, it would be good to get feedback from @teweitsai

2022-09-28 22:00 UTC, suberlak commented on tests/cwfs/test_algorithm.py
> +        self.assertIsTrue(isinstance(self.algoExp.getLog(), dict))
Apart from checking that it's a dict do you want to check that it has the keys that you expect (i..e that it got populated when debugLevel is 3) ?

2022-09-28 22:00 UTC, suberlak commented on tests/cwfs/test_algorithm.py
> +from lsst.ts.wep.Utility import CamType, DefocalType, getConfigDir, getModulePath
I wonder if this is a result of running black? If so, it would be better for those changes to be a separate PR not to be confusing (because there isn't actual content changed here, it just seems rearranged, right?)

2022-09-28 22:00 UTC, suberlak commented on tests/cwfs/test_algorithm.py
> +from lsst.ts.wep.Utility import CamType, DefocalType, getConfigDir, getModulePath
If these changes are not necessitated to pass flake and CI then I would undo

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +        if not compensated and self.defocalType == DefocalType.Extra:
According to docstring above, it would seem that  this line should be `if compensated and ...` . Or should the docstring say "If compensated is False"?

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +            If compensated is True, then extrafocal masks will be rotated by
See the comment below (should it say `If compensated is False` ?

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        num = -dI
just making sure  - does it pass the 'fft' unit tests?

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            dI, I0 = self._getdIandI0(I1, I2)
That's a good idea to align the returned elements with the function name!

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +from lsst.ts.wep.Utility import DefocalType
This doesn't seem to make any changes. If it's a result of black, see comment below - should be in a separate PR. Probably not needed to pass CI given that it passed before (?)

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> -            I1, I2 = self._applyI1I2mask_pupil(I1, I2)
Was this not necessary because the internal state of compensable images gets updated within this function?

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        # Check the image dimensions
Thanks, I didn't think it was a good idea to have a "checking" function return anything besides an error if the check doesn't go well...

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +            self.mask_comp = np.rot90(self.mask_comp, 2)
So this is done here instead of at the `_applyI1I2mask_pupil` stage (from where it was removed)? Perhaps worth mentioning that as a comment

2022-09-28 22:00 UTC, suberlak commented on tests/cwfs/test_algorithm.py
> +        self.assertIsTrue(isinstance(self.algoExp.getLog(), dict))
... and that the content of keys is what you'd assume (eg. `residZk`  is an array with 19 values, etc..)

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +                           generate_binary_structure, iterate_structure)
see comment above -  if these are purely black changes, it should be a separate PR (since there aren't any content changes that I can see, merely a rearrangement)

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +            self.mask_comp = np.rot90(self.mask_comp, 2)
Or is it instead of `_checkImageDim` rotation?

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> -        if self.defocalType == DefocalType.Extra:
Is this step done now somewhere else? Why is it not needed ?

2022-09-28 22:00 UTC, suberlak commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> -        if self.defocalType == DefocalType.Extra:
Would be useful to have some sort of a flowchart diagram saying what's the rotation of I1,I2 as we go through the algorithm (what was it before, and what your changes make), like https://confluence.lsstcorp.org/display/LTS/Algorithm+Flow+Diagram  (just because it's always been quite confusing to have so many rotations...)

2022-09-28 23:05 UTC, jbkalmbach reviewed
I don't have too much more to add beyond Chris' comments but just left a couple small notes. Looks pretty good to me.

2022-09-28 23:05 UTC, jbkalmbach commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +
Maybe move these functions up near the top of the class since they are used throughout the rest of the class.

2022-09-28 23:05 UTC, jbkalmbach commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +            If compensated is True, then extrafocal masks will be rotated by
Also note in the description what the default option is. See docstring for `_showProjection` above.

2022-09-29 13:04 UTC, teweitsai reviewed
This PR looks good to me. I think:

1. This PR contains the new feature of `log` and code refactoring. However, each PR should be for a single target to make the reviewer knows what to review (and make his/her live easier). Under this condition, you could use two or more PRs instead. If you think that is not necessary, another option is to rewrite the `git` history to have several comments and each commit is for different purpose for the reviewer to understand the details. BTW, if the code change is large, squash all changes to a single commit is not a good option in PR.

2. The name of `self.log` is a bad idea because in T&S control software, we use the `log` for the `logging` instance instead of `dict`. You could see an example here:
https://github.com/lsst-ts/ts_mtaos/blob/develop/python/lsst/ts/mtaos/model.py#L181-L184

You could see the base of control system (`ts_salobj`) as well:
https://github.com/lsst-ts/ts_salobj/blob/develop/python/lsst/ts/salobj/controller.py#L221

Therefore, please rename the `self.log` to something else to avoid the confusion with other control systems.

3. The sentence of comment is better to begin from `capital`: `# This is a comment` instead of `# this is a comment`.

4. I noticed that the `rot90()` were removed at multiple places. Is the calculation of wavefront error still right?

5. Please make sure all the Jenkins tests pass. Do not delete the failed tests unless you know what you are doing.

Thanks!

2022-09-29 13:04 UTC, teweitsai commented on doc/versionHistory.rst
> +* Added internal logging to the Algorithm class (see `Algorithm.getLog`).
`Algorithm.getLog` --> `Algorithm.getLog()`.

2022-09-29 13:04 UTC, teweitsai commented on doc/versionHistory.rst
> +  If you want the mask to match the orientation of the image post-compensation (i.e. after the 180 deg rotation), you can set `compensated=True` in `CompensableImage.makeMask`.
`CompensableImage.makeMask()`?

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        # reset the log
reset --> Reset

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            )
Please use the more detailed exception type instead such as `ValueError`:
https://docs.python.org/3/library/exceptions.html

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # the masks with compensated=True
```
# Create the masks
# These will be applied to compensated images, so we will create
# the masks with compensated=True
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # the masks with compensated=True
Why do you want to remove the word of `pupil`? In WEP, you have several coordinate systems need to consider.

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +            during compensation.
You need to document the default value in doc string.

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            # log the initial images for this iteration
```
# Log the initial images for this iteration
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the zernikes (in nm) used to compensate the images
```
# Log the Zernikes (in nm) used to compensate the images
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the compensated images for this iteration
```
# Log the compensated images for this iteration
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            # log the pupil mask that was used in the previous function, plus
```
# Log the pupil mask that was used in the previous function, plus
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            # log the residual zernikes (in nm) and wavefront
```
# Log the residual zernikes (in nm) and wavefront
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the total zernikes (in nm) and wavefront
```
# Log the total zernikes (in nm) and wavefront
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        # log the convergence
```
# Log the convergence
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the initial image
```
# Log the initial image
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
>                  # Calculate FT{S}
FFT

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log FT{S}
```
# Log FFT{S}
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the estimated wavefront
```
# Log the estimated wavefront
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the estimated signal
```
# Log the estimated signal
```

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
>              raise Exception("Images do not have the same size.")
This is a good time to use the `ValueError` here instead.

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                self.log = {}
self.log = dict()

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                self.log[outerItr]["innerLoop"][innerItr][itemName] = item
This `_logItem()` has 3 indentation layers here. Please consider to refactor it to decrease the number of layers to improve the maintainability.

2022-09-29 13:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                self.log[outerItr]["innerLoop"][innerItr][itemName] = item
BTW, please use the `dict()` instead of `{}` to assign the default value to improve the readability.

2022-09-29 16:31 UTC, teweitsai commented
I just noticed there is no unit tests for the new added functions in this PR. For each new function, please add the related unit test as well. Thanks!

2022-10-01 00:38 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +        if not compensated and self.defocalType == DefocalType.Extra:
Yeah I agree the way I wrote this sounds a little confusing. It is because the masks are calculated in the compensated orientation. I will clear this up.

2022-10-01 00:43 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +            If compensated is True, then extrafocal masks will be rotated by
Added the default and clarified the explanation.

2022-10-01 00:46 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +from lsst.ts.wep.Utility import DefocalType
Done

2022-10-01 00:48 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +                           generate_binary_structure, iterate_structure)
Done

2022-10-01 01:00 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> -        if self.defocalType == DefocalType.Extra:
Yeah there were two rotations I was able to eliminate.

There are essentially two orientations:
1. the original orientation, where the extrafocal image is rotated 180 from the intrafocal image
2. the compensated orientation, where the extrafocal image lines up with the intrafocal image

How it works now:
- the masks are generated in the compensated orientation, and never need to be rotated
- the extrafocal image is rotated to the compensated orientation during compensation. 

This extra rotation that I deleted rotated the extrafocal image *back* to the original orientation. So the algorithm had to rotate *again* to put it back into the compensated orientation (this was the rotation that was happening in `Algorithm._checkImageDim()`).

By the way,  the lack of symmetry with I1 and I2 was partly because one of these extra rotations happened to the extrafocal image, while the other happened to I2, so they only canceled eachother out when I2 was extrafocal.

2022-10-01 01:06 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> -            I1, I2 = self._applyI1I2mask_pupil(I1, I2)
Correct. Explicitly returning the images is unnecessary, and is misleading, since it suggests that the original objects are unchanged

2022-10-01 01:06 UTC, jfcrenshaw commented on tests/cwfs/test_algorithm.py
> +from lsst.ts.wep.Utility import CamType, DefocalType, getConfigDir, getModulePath
Done

2022-10-01 01:21 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +            self.mask_comp = np.rot90(self.mask_comp, 2)
It's actually a little different. This rotation is never actually relevant to the algorithm, since the algorithm calls makeMask with `compensated=True`. It just ensures that if you are looking at the original images, their masks have the correct orientation.

2022-10-01 01:25 UTC, jfcrenshaw commented on doc/versionHistory.rst
> +* Added internal logging to the Algorithm class (see `Algorithm.getLog`).
Done

2022-10-01 01:26 UTC, jfcrenshaw commented on doc/versionHistory.rst
> +  If you want the mask to match the orientation of the image post-compensation (i.e. after the 180 deg rotation), you can set `compensated=True` in `CompensableImage.makeMask`.
Done

2022-10-01 01:26 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        # reset the log
Done

2022-10-01 01:33 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            )
Ah I was just trying to match the pattern in the rest of the file. I will promote this to a ValueError!

2022-10-01 01:34 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # the masks with compensated=True
Because it creates `mask_pupil` _and_ `mask_comp`, so I thought it was misleading. But I can add the word pupil back in if you think it is appropriate?

2022-10-01 01:35 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> +            during compensation.
Done

2022-10-01 01:35 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            # log the initial images for this iteration
Done

2022-10-01 01:36 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the zernikes (in nm) used to compensate the images
Done

2022-10-01 01:36 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the compensated images for this iteration
Done

2022-10-01 01:36 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            # log the pupil mask that was used in the previous function, plus
Done

2022-10-01 01:37 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            # log the residual zernikes (in nm) and wavefront
Done

2022-10-01 01:37 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the total zernikes (in nm) and wavefront
Done

2022-10-01 01:37 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        # log the convergence
Done

2022-10-01 01:38 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
>                  # Calculate FT{S}
I dont think I understand this comment? You want me to say this is logging the FFT? Isn't this logging the image before the FFT?

2022-10-01 01:39 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
>                  # Calculate FT{S}
Done

2022-10-01 01:39 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log FT{S}
Done

2022-10-01 01:39 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the estimated wavefront
Done

2022-10-01 01:40 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the estimated signal
Done

2022-10-01 01:40 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
>              raise Exception("Images do not have the same size.")
Done

2022-10-01 01:41 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                self.log = {}
Done

2022-10-01 01:42 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # log the initial image
Done

2022-10-01 16:37 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # the masks with compensated=True
Please help to add the word of `pupil` back for the clarification. Thanks!

2022-10-06 20:33 UTC, jfcrenshaw commented on tests/cwfs/test_algorithm.py
> +        self.assertIsTrue(isinstance(self.algoExp.getLog(), dict))
Added checks for all the keys present

2022-10-06 20:33 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        num = -dI
Yep! I made sure every change left the results unchanged

2022-10-06 20:58 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                self.log[outerItr]["innerLoop"][innerItr][itemName] = item
Done!

2022-10-06 20:58 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # the masks with compensated=True
Done!

2022-10-06 21:32 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +
Done

2022-10-06 21:37 UTC, jfcrenshaw commented
Made lots of small changes in response to the above comments. The only significant change was renaming Log -> History to not cause confusion with other logging features. 

The only failing unit test has to do with donut centroids loaded from the butler. It's not clear to me how any of my changes touch that at all. Looking into this with Chris.

2022-10-10 19:49 UTC, jfcrenshaw commented
Fixed the failing test by defaulting the masks to the compensated orientation again. I thought this might happen. You can still request the masks in the orientation of the original image by setting `compensated=False` in `makeMask`.

2022-10-10 20:31 UTC, jfcrenshaw commented
I believe I have addressed all of the comments above, and all tests now pass.

I am requesting a review again. There is one potential issue: whether I need to split this into two PRs. I developed these two changes (the algorithm history, and restoring the I1/I2 symmetry) in parallel, because both of these were changing in response to the other. Now that this has converged to a final state, I could spend some time pulling the changes out into two separate PRs if needed, but would prefer not to spend this time unless we really need to. But if it's necessary, let me know!

2022-10-11 12:14 UTC, teweitsai approved these changes
This PR looks good to me. I think you could wait for Bryce's and Chris's comments as well. There are some coding style problem I think you should have the consensus with them.

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        self.history = None
You can set this as a dict first: `self.history = dict()` to let the developer notices this will be an instance of `dict` in a latter time. Then, do the similar thing at the `self.reset()` and `self.config()`. After this, you could remove the lines 525-527 at `self._recordItem()` for:

```
        # create the history if it doesn't exist
         if self.history is None:
             self.history = dict()
```

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            The debugLevel at which this item should be saved.
For the optional item, you need to put the default value in the doc string such as "(the default is xxx)".

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            self.history = dict()
You may not need this. See above comment.

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                self.history[outerItr]["innerLoop"] = dict()
You need to mention this hard-coded "innerLoop" in the doc string of function. And the type of value is `dict`.

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +    def _recordItem(self, item, itemName, outerItr, innerItr=None, debugLevel=0):
You can refer to the `self.getHistory()` in doc string for the possible keys.

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +
I am not sure @jbkalmbach wants to have this `get` function or not since he is refactoring the `ts_wep` to remove the `get`/`set` functions. In pythonic style, people do not intend to use the `get`/`set` function. I am more JAVA style when I developed this package and used to the `get`/`set` functions. You guys could discuss what to do here.

If you want to have the `get` method, you could rename the `self.history` to `self._history` to imply this is for the internal use. If you want to remove the `get` method, you can put the doc string in this function to other place because I do not want to lose it, which is very useful.

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            - converged - whether the zernikes have converged
Based on this, the `itemName` in `self._recordItem()` is restricted. It is not a random value. Therefore, you may need to add the appropriate doc string in `self._recordItem()`. Another method is to do the programmatic check before you want to record anything such as to check the available `itemName` and raise the error or something similar.

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            - converged - whether the zernikes have converged
For the physical value such as `zk` and others, put the unit in doc string.

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            self._applyI1I2mask_pupil(I1, I2)
I think in the pythonic style, if the objects `I1` and `I2` will be modified in the function, we prefer to expose this information to be:

```
I1, I2 = self._applyI1I2mask_pupil(I1, I2)
```

But in the C/C++, we do not do this.

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        # we will ignore the (1/delta z) until later in this method
Do you have a good reason for this? I felt the original implementation is more straightforward for the math. Maybe it looks slower, but it is more straightforward to understand the math behind (for the future's developers/maintainers).

2022-10-11 12:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> -        return I1, I2
I prefer to return the `I1` and `I2` if I am working in Python. For C/C++, I will not return them.

If you do not want to return them, you can mention the `I1` and `I2` will be modified in the doc string.

2022-10-11 12:14 UTC, teweitsai commented on tests/cwfs/test_algorithm.py
> +
You forgot to implement this `testSymmetryI1I2()`.

2022-10-11 12:14 UTC, teweitsai commented on tests/cwfs/test_algorithm.py
> +            with self.subTest(algo=algo):
I think you could consider to refactor this function to reduce the layers of indentation. There are 5 layers now. If it is not too hard, I would recommend the 3 indentation layers as the maximum. If you have too many layers, it would be hard to maintain.

2022-10-11 18:04 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        self.history = None
Done

2022-10-11 18:04 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            The debugLevel at which this item should be saved.
Fixed

2022-10-11 18:04 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            self.history = dict()
Done

2022-10-11 18:04 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                self.history[outerItr]["innerLoop"] = dict()
Done.

2022-10-11 18:04 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +    def _recordItem(self, item, itemName, outerItr, innerItr=None, debugLevel=0):
Done.

2022-10-11 18:05 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +
I think it makes sense to use a `getHistory` method here since the rest of this class uses `get` functions. Then the entire class can be converted to the pythonic style at the same time, rather than having two different conventions in the same class.

2022-10-11 18:08 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            - converged - whether the zernikes have converged
I added a note to the `_recordItem()` docstring that if you record any new items in the algorithm history, you should add that item to the `getHistory()` docstring. Do you think that is sufficient?

I added units for the zernikes. I don't think the wavefronts have units? If they do, I haven't been able to find the.

2022-10-11 18:44 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            self._applyI1I2mask_pupil(I1, I2)
In python, a function should either mutate something, or return something, but _not both_. Having a function return objects that it also mutates is misleading and leads to hard-to-debug errors. 

We can make this problem more obvious by writing

```python
I1_masked, I2_masked = self._applyI1I2mask_pupil(I1, I2)
```

This is misleading for two reasons:
1. It suggests that the original objects, `I1` and `I2`, are unchanged. However, this is not the case. If you inspect `I1` and `I2`, you will find that their image arrays have been masked.
2. It suggests that `I1_masked` and `I2_masked` are new objects, but again, this is not the case. `I1_masked` is just a new pointer to _the exact same object_ that `I1` points to. Changing `I1_masked` also changes `I1`, and vice versa. The same is true for `I2_masked` and `I2`.

In summary, since `self._applyI1I2mask_pupil()` mutates `I1` and `I2`, it should not return them.

2022-10-11 18:45 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            - converged - whether the zernikes have converged
The adding of note works to me.

2022-10-11 18:45 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            - converged - whether the zernikes have converged
I think the unit of wavefront is `nm` or `um`, which depends on the unit you want to hold.

2022-10-11 18:46 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +
As long as you have the consensus with Bryce, any way works to me.

2022-10-11 18:48 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            self._applyI1I2mask_pupil(I1, I2)
In this case, you can add the doc string in `self._applyI1I2mask_pupil()` to say the inputs will be mutated.

2022-10-11 19:03 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        # we will ignore the (1/delta z) until later in this method
I think you mean using `dI` and `I0` for `num` and `den`, instead of directly calculating from `I1image` and `I2image`?

I made this change to reduce code duplication: the "exp" algorithm also calculates `dI` and `I0`. Both algorithms also have to check which image is intra/extrafocal to make sure the sign of the expression is correct (this change was necessary to restore the symmetry of I1 and I2). Having both algorithms use the same function for this is easier to maintain and read, rather than having two slightly different copies in two different locations, which each have to be maintained separately.

I think it is still straightforward for the math, since it keeps everything in terms of `dI` and `I0` which are the terms used in the original math expression `# Wavefront signal S=-(1/I0)*(dI/dz)`

2022-10-11 19:07 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            self._applyI1I2mask_pupil(I1, I2)
Done!

2022-10-11 19:08 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> -        return I1, I2
Resolved in conversation above

2022-10-11 19:21 UTC, jfcrenshaw commented on tests/cwfs/test_algorithm.py
> +            with self.subTest(algo=algo):
Yeah I was worried about this... there are two problems:

1. `unittest` requires adding two layers of indentation to run the same tests on two different methods:

```python
# we will run all history tests for the exp and fft algorithms
for algo in [self.algoExp, self.algoFft]:
    with self.subTest(algo=algo):
```

I could remove this and duplicate the test code for each algorithm. That might be more readable, but would mean we have multiple copies of the same tests that have to be maintained in parallel, which is a headache.

Alternatively, I could remove this and avoid most of the code duplication by not running all of the tests for each version of the algorithm. This is probably fine, since most of the logging happens in code that is common to both algorithm versions.

2. the tests require nested for-loops because they have to traverse and check the contents of nested objects. I think these loops are harder get around.

So I could get down to three layers of indentation by eliminating problem 1. I think not running all of the tests for each algorithm version is better than just duplicating all of the test code for each. What do you think?

2022-10-11 19:23 UTC, jfcrenshaw commented on tests/cwfs/test_algorithm.py
> +
Ah yes, thank you! I should have forced the pre-implementation test to fail instead of just passing! Working on this now.

2022-10-11 19:30 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            - converged - whether the zernikes have converged
Done

2022-10-11 20:03 UTC, teweitsai commented on tests/cwfs/test_algorithm.py
> +            with self.subTest(algo=algo):
Under this condition, I would prefer to stay at the original layers of indentation to make sure we could test all the conditions. If we could come out a better realization to test all the conditions with the lower indented layers in a latter time, we could do a PR at that time. Thanks!

2022-10-11 20:04 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        # we will ignore the (1/delta z) until later in this method
If this is the case, it is fine to me.

2022-10-11 20:14 UTC, jmeyers314 commented on tests/cwfs/test_algorithm.py
> +            with self.subTest(algo=algo):
Can you dedent using a helper method?

```python
for algo in [self.algoExp, self.algoFft]: 
    with self.subTest(algo=algo):
        self.checkAlgHistory(algo)
```

2022-10-11 20:45 UTC, jfcrenshaw commented on tests/cwfs/test_algorithm.py
> +            with self.subTest(algo=algo):
Ah yes that is a smart and in hindsight incredibly obvious solution 🤦‍♂️

2022-10-11 21:22 UTC, jfcrenshaw commented on tests/cwfs/test_algorithm.py
> +
Done.

2022-10-11 21:22 UTC, jfcrenshaw commented on tests/cwfs/test_algorithm.py
> +            with self.subTest(algo=algo):
Done. I used the same structure for testing the I1 <-> I2 symmetry for both algorithms

2022-10-31 22:22 UTC, suberlak requested changes

2022-10-31 22:22 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +
Did @jbkalmbach  weigh in ?  Does it affect adding `get` to any other elements of `Algorithm` ?

2022-10-31 22:22 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        signal = history[2]["innerLoop"][3]["estS"]
If the `history` dic starts with 0, isn't ` history[2]` for 3rd step of the outer loop?

2022-10-31 22:22 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
>              with the previous iteration. (the default is 1e-3.)
I'd add `iteration of the outer loop` to be more clear

2022-10-31 22:22 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            # Record the residual zernikes (in nm) and wavefront
I think `Zernike coefficients`  is used elsewhere throughout `ts_wep`, just like "Legendre polynomials" or "Bessels functions"   - this is because Fritz Zernike is a name https://telescope-optics.net/zernike_aberrations.htm

2022-10-31 22:22 UTC, suberlak commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # Record the total zernikes (in nm) and wavefront
Same as above - `Zernike coefficients` or `combined coefficients of Zernike polynomials`...

2022-10-31 22:22 UTC, suberlak commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> -        if self.defocalType == DefocalType.Extra:
thanks for the clarification! Would be useful to add that info somewhere in the docs (README ?) so it doesn't get lost in the graveyard of closed PRs and deleted branches

2022-11-02 21:50 UTC, jbkalmbach commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +
Sure, it makes sense to just convert everything over at the same time. But I would agree with Te-Wei that if you are going to use a `get` function then rename `self.history` to `self._history` to imply that it should only be for internal use.

2022-11-03 20:55 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/CompensableImage.py
> -        if self.defocalType == DefocalType.Extra:
@suberlak I added a section about this to the bottom of the README. Would you mind reading it and letting me know if you think it needs any changes?

2022-11-03 20:55 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +
Done.

2022-11-03 20:55 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +        signal = history[2]["innerLoop"][3]["estS"]
Nice catch! Fixed.

2022-11-03 20:56 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
>              with the previous iteration. (the default is 1e-3.)
Done.

2022-11-03 20:56 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +            # Record the residual zernikes (in nm) and wavefront
Done.

2022-11-03 20:56 UTC, jfcrenshaw commented on python/lsst/ts/wep/cwfs/Algorithm.py
> +                # Record the total zernikes (in nm) and wavefront
Done.

2022-11-09 19:43 UTC, suberlak requested changes
Thanks for updating the README!

2022-11-09 19:43 UTC, suberlak commented on README.md
> +***tl;dr***
small thing, but I think that's too informal for `ts` package if you ask me

2022-11-09 19:43 UTC, suberlak commented on README.md
> +***Therefore, we do not need to explicitly rotate images or masks during the algorithm.***
Perhaps I'm not the best person to judge, but run "rotate ... during the algorithm" by someone else - does it seem odd just to me? Seems like a verb is missing or rephrase needed eg. "rotate ... during the execution of the algorithm" or "rotate... inside the algorithm..."

2022-11-09 19:43 UTC, suberlak commented on README.md
> +A pair of intra- and extra-focal donuts is used to approximate the gradient of the donut intensity with respect to the focal direction (i.e. the left side of [Xin 2015](https://ui.adsabs.harvard.edu/
MNRAS always preferred "right hand side", "left hand side" to just "left side"... Is it just BE vs AE or an actual style improvement?

2022-11-09 19:43 UTC, suberlak commented on README.md
> +However, before calculating the mean and difference intensities, the donuts are mapped to the pupil plane and "compensated" for the current best-guess of the optical aberations ([Xin 2015](https://ui
"aberrations" (typo)

2022-11-10 17:45 UTC, jfcrenshaw commented on README.md
> +***tl;dr***
Okay, I changed this to "Summary"!

2022-11-10 17:45 UTC, jfcrenshaw commented on README.md
> +***Therefore, we do not need to explicitly rotate images or masks during the algorithm.***
Changed this to "inside the algorithm".

2022-11-10 17:50 UTC, jfcrenshaw commented on README.md
> +A pair of intra- and extra-focal donuts is used to approximate the gradient of the donut intensity with respect to the focal direction (i.e. the left side of [Xin 2015](https://ui.adsabs.harvard.edu/
I googled this, and they're usually interchangeable, but apparently it's convention in mathematics in use "right-hand side" and "left-hand side" because this matches the commonly-used abbreviations "RHS" and "LHS".

So I changed this to "right-hand side", etc.

2022-11-10 17:54 UTC, jfcrenshaw commented on README.md
> +However, before calculating the mean and difference intensities, the donuts are mapped to the pupil plane and "compensated" for the current best-guess of the optical aberations ([Xin 2015](https://ui
🙏

2022-11-18 17:38 UTC, suberlak approved these changes
Already reviewed the README changes, thanks for improvement!

2022-11-21 18:37 UTC, merged