Tickets/DM-36304: remove imageCoCenter
lsst-ts/ts_wep_older pull request #154
Opened 2022-11-01 18:56 UTC by suberlak

Given the results of https://jira.lsstcorp.org/browse/DM-36714  and https://jira.lsstcorp.org/browse/DM-36304 , I open this PR to remove the `imageCoCenter` step, given that it makes no difference on the result of the calculation, and therefore saves extra computational time. To summarize these tickets, it has been found that the amount of shift imparted by `imageCoCenter` , being by design `<6` pixels (assuming defocal offset of `1.5` mm and pixels size `10` microns), makes no difference on the recovered Zernikes. This is because this minute shift is counteracted for in the `compensate` step where images are  transformed to the pupil plane, and `recentered`, to match the center of the projection template to the center of each donut. Simulations showed that the shift imparted  by `imageCoCenter` would have to exceed `~9` pixels to make any difference to the results of running the CWFS algorithm.

2022-11-10 21:34 UTC, jbkalmbach commented
Ok, sorry about the wait. I've verified that this does not affect my masked deblending results on comcam either.

2022-11-10 21:35 UTC, jbkalmbach requested changes, later dismissed
Removing this step from `Algorithm.py` is good with me, but check with @teweitsai about the proper way to deprecate a function with a warning that it will be deleted at a later date rather than deleting it all at once from `CompensableImage.py`.

2022-11-10 21:36 UTC, jbkalmbach commented
See here for a deprecationWarning example: https://github.com/lsst-ts/ts_wep/blob/d41a81fe380c09432950d0db933e7b664b8782ea/python/lsst/ts/wep/cwfs/Tool.py#L64-L68

2022-12-02 12:10 UTC, teweitsai approved these changes
Thanks for this improvement and deprecation warning to let people have time to update the code!

2022-12-06 20:07 UTC, merged