tickets/DM-37289: Port Latiss functionality into new pipeline and deprecate EstimateZernikesTasks
lsst-ts/ts_wep_older pull request #159
Opened 2022-12-09 00:53 UTC by jbkalmbach

2022-12-09 00:53 UTC, jbkalmbach commented
Adding @suberlak as review to make sure Latiss functionality all moved over.

2022-12-09 12:10 UTC, teweitsai commented
I felt the `CutOutDonutsLatissTask.py` is a duplicated code. Is it possible to update the `CutOutDonutsTask` to use the configuration to identify the different instrument and provide the related business logic? Or this will increase the code complexity?

2022-12-09 23:47 UTC, jbkalmbach commented
> I felt the `CutOutDonutsLatissTask.py` is a duplicated code. Is it possible to update the `CutOutDonutsTask` to use the configuration to identify the different instrument and provide the related business logic? Or this will increase the code complexity?

Hi @teweitsai. I think I addressed your concern by moving the LATISS functionality in to `CutOutDonutsScienceSensorTask` instead of making a brand new task since as you said a lot of the functionality was already there.

2022-12-13 01:14 UTC, suberlak commented on tests/testData/pipelineConfigs/testCutoutsLatissPipeline.yaml
> +    class: lsst.ts.wep.task.GenerateDonutDirectDetectTask.GenerateDonutDirectDetectTask
for LATISS I've used before 'MEDIAN_PER_ROW' https://github.com/lsst-ts/ts_wep/blob/96ffe9be7795e9dd6d3627880e17b49a9dbea414/tests/testData/pipelineConfigs/testLatissPipeline.yaml#L24   . Why is this different?  Have you tested that it works better?

2022-12-13 01:14 UTC, suberlak commented on python/lsst/ts/wep/task/CutOutDonutsScienceSensorTask.py
> +        elif cameraName == "LATISS":
It appears to be a port of https://github.com/lsst-ts/ts_wep/blob/96ffe9be7795e9dd6d3627880e17b49a9dbea414/python/lsst/ts/wep/task/EstimateZernikesLatissTask.py#L112  , yes?

2022-12-13 01:53 UTC, suberlak requested changes
Thanks for the improvement!

2022-12-13 01:53 UTC, suberlak commented on policy/cwfs/instData/auxTel/instParamCalcZernikesConfig.yaml
> +description: LATISS Telescope Parameters
It's such a long code reorganization that it is a but difficult to reverse-engineer to figure out what was the intention (the ticket https://jira.lsstcorp.org/browse/DM-37289 doesn't provide any details). By the look of files I'm guessing that some functionality of `EstimateZernikes` is split into two tasks, `cutOutDonuts` and `calcZernikes`  .  By looking at files it seems that some configs are a copy-paste from another config. I would find it very helpful to see the executive summary of intended changes + a trace of which configs went from where to where.  Since majority of the code seems to be moved rather than written from the scratch, it would help also find out what's new.

2022-12-13 01:53 UTC, suberlak commented on policy/cwfs/instData/auxTel/instParamCalcZernikesConfig.yaml
> +      instObscuration: 0.3525
For instance this data seems to be related to https://github.com/lsst-ts/ts_wep/blob/develop/policy/cwfs/instData/auxTel/instParamPipeConfig.yaml  . Is the `instParamPipeConfig` being removed? Are we duplicating any configs anywhere (because if yes, then any change to any parameter would have to be propagated everywhere, would be good to have one place for a parameter that is intended to be describing the instrument).

2022-12-13 01:53 UTC, suberlak commented on python/lsst/ts/wep/task/CutOutDonutsScienceSensorTask.py
> +    def assignExtraIntraIdx(self, focusZVal0, focusZVal1, cameraName):
Is this a combination of what was hitherto in https://github.com/lsst-ts/ts_wep/blob/96ffe9be7795e9dd6d3627880e17b49a9dbea414/python/lsst/ts/wep/task/EstimateZernikesLatissTask.py#L112  and https://github.com/lsst-ts/ts_wep/blob/96ffe9be7795e9dd6d3627880e17b49a9dbea414/python/lsst/ts/wep/task/EstimateZernikesScienceSensorTask.py#L93 ?

2022-12-13 01:53 UTC, suberlak commented on python/lsst/ts/wep/task/CutOutDonutsScienceSensorTask.py
> +                "Invalid cameraName parameter: {cameraName}. Camera must  "
Did you check that the error string provides correct error ? The f-string appears to be missing the f....   ( `f"Invalid...{cameraName}")`

2022-12-13 01:53 UTC, suberlak commented on tests/task/test_cutOutDonutsScienceSensorTask.py
> +            "Invalid cameraName parameter: {cameraName}. Camera must  "
Does this f-string miss the `f` as above?  Does it pass the appropriate (erroneous) `{cameraName}` ?

2022-12-13 01:53 UTC, suberlak commented on tests/task/test_cutOutDonutsLatissTask.py
> +        for donutStamp, cutOutStamp in zip(taskOut.donutStampsIntra, testIntraStamps):
If I understand correctly this checks if donuts are the same when the task is run as a pipetask with `run` or whether the `cutOutStamps` is called from the `task` itself. But it doesn't check if any donuts are actually there...

2022-12-13 01:53 UTC, suberlak commented on tests/task/test_cutOutDonutsLatissTask.py
> +        )
Perhaps here you want to add testing whether `task.assignExtraIntraIdx` throws a correct error when eg. `Hubble`  is passed as `instrument` ?

2022-12-13 01:53 UTC, suberlak commented on tests/task/test_cutOutDonutsLatissTask.py
> +        )
Just like below in `testAssignExtraIntraIdxInvalidCamera` in `test_cutOutDonutsScienceSensorTask` ?

2022-12-13 01:53 UTC, suberlak commented on tests/task/test_generateDonutDirectDetectTask.py
>          truth_x = np.sort(np.array([3815, 2814, 2811, 3812]))
Is this the result of running yet another version of black?  I wonder if it could be a separate PR (unless it fails CI)

2022-12-13 01:53 UTC, suberlak commented on tests/testData/pipelineConfigs/testCalcZernikesLatissPipeline.yaml
> +      python: OverscanCorrectionTask.ConfigClass.fitType = 'MEDIAN'
Is this using parts of https://github.com/lsst-ts/ts_wep/blob/develop/tests/testData/pipelineConfigs/testLatissPipeline.yaml ? If so, the `fitType` that worked before was `MEDIAN_PER_ROW`. Did you see better postISR image quality with `MEDIAN` ?

2022-12-13 18:22 UTC, jbkalmbach commented on tests/testData/pipelineConfigs/testCutoutsLatissPipeline.yaml
> +    class: lsst.ts.wep.task.GenerateDonutDirectDetectTask.GenerateDonutDirectDetectTask
No, I think I just copied over the FAM values and didn't notice the difference in the LATISS task. I'll update that.

2022-12-13 18:22 UTC, jbkalmbach commented on python/lsst/ts/wep/task/CutOutDonutsScienceSensorTask.py
> +        elif cameraName == "LATISS":
Yes

2022-12-13 18:23 UTC, jbkalmbach commented on python/lsst/ts/wep/task/CutOutDonutsScienceSensorTask.py
> +    def assignExtraIntraIdx(self, focusZVal0, focusZVal1, cameraName):
Yes, as a way to reduce duplication as mentioned by Te-Wei above.

2022-12-13 18:25 UTC, jbkalmbach commented on tests/testData/pipelineConfigs/testCalcZernikesLatissPipeline.yaml
> +      python: OverscanCorrectionTask.ConfigClass.fitType = 'MEDIAN'
No, just the same thing as the cutouts config. Updated.

2022-12-13 18:30 UTC, jbkalmbach commented on tests/task/test_generateDonutDirectDetectTask.py
>          truth_x = np.sort(np.array([3815, 2814, 2811, 3812]))
Sure, this can wait for another PR

2022-12-13 18:33 UTC, jbkalmbach commented on python/lsst/ts/wep/task/CutOutDonutsScienceSensorTask.py
> +                "Invalid cameraName parameter: {cameraName}. Camera must  "
Looks like the test and this are both missing the f designation so they were passing but with the wrong message. Fixed now.

2022-12-13 18:38 UTC, jbkalmbach commented on tests/task/test_cutOutDonutsLatissTask.py
> +        )
I don't think that's necessary because it uses the same function so I would just be testing the same behavior on the same piece of code.

2022-12-13 22:17 UTC, jbkalmbach commented on tests/task/test_cutOutDonutsLatissTask.py
> +        for donutStamp, cutOutStamp in zip(taskOut.donutStampsIntra, testIntraStamps):
Adding in some tests on the donut catalog content.

2022-12-13 22:23 UTC, jbkalmbach commented on policy/cwfs/instData/auxTel/instParamCalcZernikesConfig.yaml
> +description: LATISS Telescope Parameters
There actually wasn't that much capability that needed to be ported into the new pipelines. The only thing was adding the additional `assignExtraIntraIdx` functionality into `CutOutDonutsScienceSensor`. 

Almost all of the new code is adding tests specifically for the LATISS based upon the `test_estimateZernikesLatissTask` tests you originally wrote.

We already have documentation on the `CutOutDonuts` and `CalcZernikes` tasks in notebooks here: https://github.com/lsst-ts/ts_analysis_notebooks/tree/develop/aos/closed_loop that show how to use them.

I'll answer questions about configs in response to your comment below.

2022-12-13 22:27 UTC, jbkalmbach commented on policy/cwfs/instData/auxTel/instParamCalcZernikesConfig.yaml
> +      instObscuration: 0.3525
`instParamPipeConfig` only works with the `EstimateZernikesTask` family of tasks (you can see the tasks prescribed by that yaml). This file is the equivalent but using the new pipeline tasks. When we remove the `EstimateZernikes` tasks in the future we can change the `instParamPipeConfig` files to use the `CutOutDonuts` and `CalcZernikes` tasks as this new file here does. Or if you think it would be better just to switch everything over now I could do that?

2022-12-14 12:07 UTC, teweitsai commented on policy/cwfs/instData/auxTel/instParamCalcZernikesConfig.yaml
> +      instObscuration: 0.3525
I think we do begin to have the duplication of configuration files.
In the TS control systems, we have the default configuration file and the overwrite file.
For example: https://github.com/lsst-ts/ts_config_mttcs/tree/develop/MTM2/v2

The default is `_init.yaml`.
The content in `_summit.yaml` will overwrite the existed setting in `_init.yaml`.
I think we could have a similar thing for the `ts_wep` to minimize the duplication of configuration file.
It should be easier in future if we need to remove a task and add others new.

BTW, do we still need this:
https://github.com/lsst-ts/ts_wep/blob/tickets/DM-37289/policy/cwfs/donutTemplateData/phosimTemplates/.gitkeep

2022-12-14 18:50 UTC, jbkalmbach commented on policy/cwfs/instData/auxTel/instParamCalcZernikesConfig.yaml
> +      instObscuration: 0.3525
Ok, since I'm deprecating the `EstimateZernikes` I will just replace the default configuration files with the new pipeline and we will only have one file for each instrument.

And yes, I think we should keep that for now since we still have the functionality to add phosimTemplates but we just haven't been using them. Maybe in the future we can test batoid templates and then decide what to do with that.

2022-12-20 02:08 UTC, suberlak approved these changes
Looks good, thanks for the update!

2022-12-23 22:10 UTC, merged