Add documentation explaining how to run the WEP pipeline on the USDF batch system
lsst-ts/ts_wep_older pull request #175
Opened 2023-03-24 22:54 UTC by jbkalmbach

2023-06-08 23:06 UTC, jmeyers314 requested changes
Hi Bryce,
  Sorry this has been so slow.  Looks mostly good to me, I just had a few questions/comments.

2023-06-08 23:06 UTC, jmeyers314 commented on doc/user-guide/wepBatchProcessing.rst
> +         dataQuery: exposure in (2023020200434, 2023020200435)
This corresponds to one intra and one extra focal exposure I think, right?  Might want to clarify that.

2023-06-08 23:06 UTC, jmeyers314 commented on doc/user-guide/wepBatchProcessing.rst
> +    - The `-n 20 -c 32` options request 20 individual glide-in slots of size 32 cores each (each is a Slurm job that obtains a partial node).
This seems way overkill for the single pair of exposures in the example below.  Maybe say something about what reasonable ranges are for a given kind of run?

2023-06-08 23:06 UTC, jmeyers314 commented on doc/user-guide/wepBatchProcessing.rst
> +2. Now one can run the `ctrl_bps_htcondor <https://pipelines.lsst.io/modules/lsst.ctrl.bps.htcondor/userguide.html>` workflow
I'm not sure this is an actual step, no?  Could just be the first sentence after combining the current steps 2 & 3.

2023-06-08 23:06 UTC, jmeyers314 commented on doc/user-guide/wepBatchProcessing.rst
> +    bps submit -d "exposure.observation_type='cwfs' and exposure.day_obs=20220912 and exposure.seq_num in (96..97)"  bps_wep_test.yaml
Should add a note about where to expect the output to be available.  I.e., what is the default collection and how to override that if desired.

2023-06-21 23:06 UTC, jbkalmbach commented on doc/user-guide/wepBatchProcessing.rst
> +    - The `-n 20 -c 32` options request 20 individual glide-in slots of size 32 cores each (each is a Slurm job that obtains a partial node).
Adding suggestions on running with WEP and appropriate `-n` and `-c` values.

2023-06-21 23:31 UTC, jbkalmbach commented on doc/user-guide/wepBatchProcessing.rst
> +    bps submit -d "exposure.observation_type='cwfs' and exposure.day_obs=20220912 and exposure.seq_num in (96..97)"  bps_wep_test.yaml
Added that information and a link to the `bps submit` documentation.

2023-06-22 00:07 UTC, jmeyers314 approved these changes

2023-06-22 00:07 UTC, jmeyers314 commented
Thanks Bryce.  LGTM!

2023-06-22 14:17 UTC, merged