Add FitWcs Task
lsst-ts/ts_wep_older pull request #179
Opened 2023-04-18 17:00 UTC by jbkalmbach

2023-04-27 20:34 UTC, suberlak requested changes
Thanks for the update! If`README` could be updated with the intended use case for this task it would be very helpful.

2023-04-27 20:34 UTC, suberlak commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +        name="gaia_dr2_20200414",
I understand this is a required connection. If in the future some other name was to be used (rather than `20200414` version), would it necessitate change in `ts_wep`? Could it take the name of the catalog from config?

2023-04-27 20:34 UTC, suberlak commented on tests/task/test_generateDonutDirectDetectTask.py
> +# This file is part of ts_wep.
Is this preamble change meant to be part of this PR?

2023-04-27 20:34 UTC, suberlak commented on tests/task/test_generateDonutDirectDetectTask.py
> +# This file is part of ts_wep.
Because otherwise nothing seems to have changed in `generateDonutDirectDetect`...

2023-04-27 20:34 UTC, suberlak commented on tests/task/test_fitWcsFromDetectedTask.py
> +        collections = "refcats/largeCatSingleCCD,LSSTCam/calib,LSSTCam/raw/all"
If I understand correctly, this test is using simulated image with an associated reference catalog that was created based on the star catalog. Do you want to include some real exposure (eg. auxTel) using the real refcat (such as the required connection `gaia_dr2_20200414` ? )

2023-04-27 20:34 UTC, suberlak commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +        name="preFitPostISRCCD",
Since this input exposure needs to have a specific name `preFitPostISRCCD` to work (or could it be set in the `config` ? ), it would be good to mention the addition of this task in `README`,  and that the intended usage is: 
*  run `ISR` creating `preFitPostISRCCD`
* run the `generateDonutDirectDetect` to get donut catalog
* run `fitWcsFromDetected`  to refit for WCS
* (optional : run `generateDonutCatalogWcsTask` to get the updated donut catalog)
* cutout donuts with `cutOutDonutsScienceSensorTask`
* use `calcZernikesTask` to fit the wavefront given the donut postage stamp images

2023-04-27 20:34 UTC, suberlak commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +    # Took these defaults from atmospec/centroiding
can you expand what `atmospec/centroiding` pertains to ?

2023-04-27 20:34 UTC, suberlak commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +        self.astromTask.referenceSelector.doMagLimit = True
So if we happen to have donuts fainter than that in some edge case, and the WCS fit fails,   will it allow eg. to skip using `generateDonutCatalogWcsTask`, but proceed to the next step (`cutOutDonuts` and `calcZernikes` ) using the donut catalog from `generateDonutDirectDetect` ? So that in a sense,  the WCS fitting could be used as an extra option - "try to refit WCS, but if it fails, still use the direct detection donut locations to do wavefront estimation".

2023-04-27 20:52 UTC, jbkalmbach commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +        name="gaia_dr2_20200414",
Yes, the config overrides this. As an example you can see the pipeline config file in this PR tells it to use `cal_ref_cat`.

2023-04-27 20:53 UTC, jbkalmbach commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +        name="gaia_dr2_20200414",
So to answer your question, no change would be necessary here.

2023-04-27 20:55 UTC, jbkalmbach commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +        self.astromTask.referenceSelector.doMagLimit = True
Not the way it is currently designed because of the way the connections are specified as they flow through the pipeline. If we want that in the future we could try to redesign this task and `generateDonutCatalogWcsTask` so that this task would be an optional subtask within `generateDonutCatalogWcsTask`.

2023-04-27 20:58 UTC, jbkalmbach commented on tests/task/test_fitWcsFromDetectedTask.py
> +        collections = "refcats/largeCatSingleCCD,LSSTCam/calib,LSSTCam/raw/all"
I have a notebook ready in `ts_analysis_notebooks` that will demonstrate this on real data. But for the tests requiring a connection to `gaia_dr2_20200414` would mean you could only run it on machines that was available and this test wouldn't be portable so it wouldn't be consistently tested on Jenkins for example.

2023-04-27 20:59 UTC, jbkalmbach commented on tests/task/test_generateDonutDirectDetectTask.py
> +# This file is part of ts_wep.
I will make it a separate PR.

2023-04-27 21:07 UTC, jbkalmbach commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +    # Took these defaults from atmospec/centroiding
Adding a link to the code and describing why it's relevant.

2023-04-27 21:44 UTC, teweitsai commented
Please help to update the `doc/taskClass.uml`, `doc/developer-guide/developer-guide.rst` , and other documents to reflect the new task class in this PR.

2023-04-28 22:37 UTC, jbkalmbach commented
Ok, I actually made some big changes so that this task will generate the catalogs as well. This makes the pipeline more robust since it can handle WCS fit failures by just returning the same exposure WCS and the directDetectCatalog. I also added information on the success of the WCS fit into the task metadata to make it easily available.

2023-04-28 22:38 UTC, jbkalmbach commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +        name="preFitPostISRCCD",
Ok, I think this should all be in the README now. And it should be simpler with the elimination of the need to add `generateDonutCatalogWcsTask` into the pipeline.

2023-04-28 22:39 UTC, jbkalmbach commented
If the changes are enough that it would be better to open a new PR let me know.

2023-05-01 18:22 UTC, suberlak approved these changes
It's more overall comment for clarity: since the intended usage would be now to run `generateDonutDirectDetect`,  then try `fitWcsFromDetected`  (which may provide a new donut catalog),  would it be be better to  eg. call the new task `generateDonutF
romRefitWcs` or something like that ? (to imply that just like for `generateDonutDirectDetect` and `generateDonutCatalogWcs` , the intended outcome is a new donut catalog)

2023-05-01 18:22 UTC, suberlak commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +
So if no catalogs cover the detector (i.e. WCS fit was successful both the refCat used has no sources in the requested region), will the original donut catalog from direct detection be returned, just like for a failed WCS case?

2023-05-01 18:22 UTC, suberlak commented on python/lsst/ts/wep/task/generateDonutCatalogWcsTask.py
> -from lsst.meas.algorithms.sourceSelector import ReferenceSourceSelectorTask
I wonder what makes this not needed anymore (I'm glad it isn't, but is it removed because it's a good update anyway, or is it somehow related to the WCS fit task?)

2023-05-01 18:41 UTC, jbkalmbach commented on python/lsst/ts/wep/task/fitWcsFromDetectedTask.py
> +
Good point. Let me add some code to make that happen and a test case for it.

2023-05-01 18:43 UTC, jbkalmbach commented on python/lsst/ts/wep/task/generateDonutCatalogWcsTask.py
> -from lsst.meas.algorithms.sourceSelector import ReferenceSourceSelectorTask
Yeah, all of the selection code occurs within the `DonutSourceSelectorTask` now so it's all in one place and this isn't necessary anymore as a result.

2023-05-01 18:44 UTC, jbkalmbach commented
> It's more overall comment for clarity: since the intended usage would be now to run `generateDonutDirectDetect`, then try `fitWcsFromDetected` (which may provide a new donut catalog), would it be be better to eg. call the new task `generateDonutFromRefitWcs` or something like that ? (to imply that just like for `generateDonutDirectDetect` and `generateDonutCatalogWcs` , the intended outcome is a new donut catalog)

Yeah, that makes sense. I'll change the name to `generateDonutFromRefitWcs`.

2023-05-02 22:53 UTC, merged