Tickets/DM-42228: add donut quality check
lsst-ts/ts_wep_older pull request #222
Opened 2024-03-14 20:44 UTC by suberlak

2024-03-20 20:11 UTC, jbkalmbach commented on doc/versionHistory.rst
> +=======
This should be removed, possibly this is left over from a merge conflict?

2024-03-20 20:11 UTC, jbkalmbach commented on python/lsst/ts/wep/task/estimateZernikesBase.py
> +        # Exclude stamps that are not effective
Can you create a config and make this an optional step? It would be easier for debugging things in the future if we can easily turn this on and off when running the pipeline.

2024-03-20 20:11 UTC, jbkalmbach commented on python/lsst/ts/wep/task/estimateZernikesBase.py
> +            zip(donutStampsExtraSelect, donutStampsIntraSelect)
How do we keep track of which Zernike estimates go with which donut in the end? I think we discussed adding in flags to the `CalcZernikesTask` to identify?

2024-03-20 20:11 UTC, jbkalmbach commented on python/lsst/ts/wep/task/donutStamp.py
> +            # "EFFECTIVE" is a measure of entropy-based information content
Can you add something here to indicate this is a signal-to-noise effectiveness measure? Otherwise it's pretty vague.

2024-03-20 20:11 UTC, jbkalmbach commented on python/lsst/ts/wep/task/donutStamps.py
> +        Get the effectiveness measure for each stamp.
Also can you add something indicating this is related to SNR?

2024-05-17 22:48 UTC, jbkalmbach requested changes
I don't think it needs any really extensive changes. Marking as request changes because there's a lot more tests I'd like to see added and also the existing tests don't seem to be passing on Jenkins.

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/donutImageCheck.py
> +        if self.returnEntro:
Can you add a new test to check this works correctly?

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +            + "The default S/N = 5000 corresponds to the default entropy threshold (3.5)"
I don't understand why S/N = 5000 is necessarily equivalent to an entropy of 3.5. Where does this come from?

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +        default=False,
If both `selectWithSingalToNoise` and `selectWithEntropy` are both `True` what is the functionality when it passes only one test? Is it logical and or does one take priority? Please add some more documentation explaining what happens in that situation as well as adding tests to verify that the expected behavior is what you see.

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +                donutsExtraQuality=[],
I think these should be empty dataframes. You should add a test that checks the pipeline runs with empty content because I think this should fail since it doesn't match the output described in the `connections` class.

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +        # Which donuts to use for Zernike estimation
This logic (down to line 226) should be moved to its own function. This needs tests as well and moving it to its own function will make it simpler to test.

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +        # AND condition : if both selectWithEntropy
Ah okay. I see this answers my question in the comments above. Can you just add this to the docstrings for the configs too? Still add a test to verify behavior.

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +    )
Should we have a way to check that there is still some background in the stamp left? Or some max number of iterations based upon the mask and stamp size? Is that a worry?

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +
Remove extra empty line

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +        # maskPlaneDict={'BAD': 0, 'BLEND': 10, 'CR': 3, 'DETECTED': 5,
Just to be clear. None of these values will show up in the mask when using `makeMask` except 9 and 10 right? A comment to clarify would be good here and help make the values you calculate in the next paragraph make sense.

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +        # Avoid zero division in case variance plane doesn't exist
Does this mean we throw away all donuts in an image where the variance plane doesn't exist? In what cases do we expect the variance plane to have errors like that?

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +        drCentroidList = list()
Change to separate dx, dy as mentioned in today's AOS meeting.

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +        # Save the donut flux as magnitude
What happens when you have this branch set up and you try to load butler datasets with old donut stamps? Do you run into errors?

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsCwfsTask.py
> +        # The order of donut catalogs is the same
I think these changes should be rolled back. When running interactively a user might not know that they should put in extra, intra in order. Maybe what we should do is make an issue to find a way to force the `donutCatalogs` to have the same test as the exposures?

2024-05-17 22:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsCwfsTask.py
> +        # The order of donut catalogs is the same
Could be as simple as including the detector name in our donut catalogs.

2024-05-17 22:48 UTC, jbkalmbach commented on tests/task/test_calcZernikesTieTaskScienceSensor.py
> +        np.testing.assert_array_equal(np.sort(colnames), np.sort(desired_colnames))
As mentioned above we should test the actual logic inside the selection code.

2024-05-17 22:48 UTC, jbkalmbach commented on tests/task/test_cutOutDonutsBase.py
> +        np.testing.assert_array_almost_equal(sn_values, sn_calculated, decimal=4)
Can you add a test that runs the pipeline and verifies all the metadata gets stored in the butler and when you pull the donut stamp from the repository that it still has all the metadata you added? I wonder if because the `DonutStamps` class doesn't know about these if they get loaded correctly.

2024-07-09 01:13 UTC, suberlak commented on python/lsst/ts/wep/donutImageCheck.py
> +        if self.returnEntro:
test added

2024-08-01 20:21 UTC, suberlak commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +                donutsExtraQuality=[],
added a test for that, and changed list to empty DF.

2024-08-01 20:22 UTC, suberlak commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +        # Which donuts to use for Zernike estimation
Made a new function and added tests for it

2024-08-01 20:50 UTC, suberlak commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +    )
Added checking for that

2024-08-01 21:03 UTC, suberlak commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +        # maskPlaneDict={'BAD': 0, 'BLEND': 10, 'CR': 3, 'DETECTED': 5,
They actually do - I've seen them in various variations, so eg. 1024 and 2048 are not the only values.

2024-08-01 21:04 UTC, suberlak commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +        # Avoid zero division in case variance plane doesn't exist
Clarified that we'll use the background variance estimate for SN in that case, added a log message.

2024-08-01 21:22 UTC, suberlak commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +        # Save the donut flux as magnitude
It would work fine-  all quantities are calculated here, and those that are not (variance plane) can be replaced with background image variance. I added necessary legacy behavior for donutCatalog that do not have 'detector' column in cutOutDonutsCwfs.

2024-08-01 21:23 UTC, suberlak commented on python/lsst/ts/wep/task/cutOutDonutsCwfsTask.py
> +        # The order of donut catalogs is the same
Added detector name to donut catalog so that we test for order, as well as legacy behavior.

2024-08-01 21:23 UTC, suberlak commented on tests/task/test_calcZernikesTieTaskScienceSensor.py
> +        np.testing.assert_array_equal(np.sort(colnames), np.sort(desired_colnames))
added a test for `selectDonuts` function

2024-08-02 05:09 UTC, suberlak commented on tests/task/test_cutOutDonutsBase.py
> +        np.testing.assert_array_almost_equal(sn_values, sn_calculated, decimal=4)
Added that to test for `cutOutDonutsScienceSensorTask`, since that's where the pipeline is run.

2024-08-02 22:09 UTC, jbkalmbach reviewed
Sorry, I know you've done a lot of coding already for this but I think we should split off the selection step in `CalcZernikes` into a subtask.

2024-08-02 22:09 UTC, jbkalmbach commented on policy/snLimitStar.yaml
> +# See
It looks like the documentation here is incomplete.

2024-08-02 22:09 UTC, jbkalmbach commented on tests/task/test_cutOutDonutsScienceSensorTask.py
> +        # Check that the  new metadata is stored in butler
Extra space between "the" and "new"

2024-08-02 22:09 UTC, jbkalmbach commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +
What do you think about moving all the selectDonuts code into a subtask that can be loaded like the `combineZernikes` and `estimateZernikes` subtasks? I think it would make things a lot cleaner and be easier to turn on and off if we want to do some debugging. We do the same for selecting donuts when making the original catalogs so I think it makes sense to do it here too.

2024-08-02 22:09 UTC, jbkalmbach commented on python/lsst/ts/wep/task/cutOutDonutsBase.py
> +
Remove empty line after comment

2024-08-02 23:18 UTC, jbkalmbach commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +
Like we do here: https://github.com/lsst-ts/ts_wep/blob/8ac739e3d3dc4b0f4859ded9b7e7a0bcf968bb9f/python/lsst/ts/wep/task/generateDonutCatalogWcsTask.py#L116-L117

2024-08-07 22:56 UTC, suberlak commented on python/lsst/ts/wep/task/calcZernikesTask.py
> +
Moved to a new task, added new tests.

2024-08-13 21:48 UTC, jbkalmbach approved these changes
Thanks for the changes. Looks good. Just a few comments. 

Also, one last ask. Can you run the closed loop and post a convergence plot before merging just to make sure that looks good with your default values? Maybe you've already done this.

2024-08-13 21:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/calcZernikesTask.py
>      )
Can you add a `doDonutStampSelector` config as well and use it to enable/disable donutStampSelector?

2024-08-13 21:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/donutStampSelectorTask.py
> +
Don't need these empty lines between each config.

2024-08-13 21:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/donutStampSelectorTask.py
> +            self.log.warning("Entropy not in donut stamps metadata. Using all donuts.")
Maybe instead of "using all donuts." change to something like "No entropy cut. Checking if signal-to-noise should be applied."

2024-08-13 21:48 UTC, jbkalmbach commented on python/lsst/ts/wep/task/donutStampSelectorTask.py
> +            self.log.warning("SN not in donut stamps metadata. Using all donuts.")
Like above, all donuts being used isn't necessarily true if entropy cut was applied. Should change to indicate that this only means SNR cut wasn't applied.

2024-08-28 17:01 UTC, suberlak commented
Convergence plot running `img_closed_loop` with stamp selection on 
<img width="598" alt="Screenshot 2024-08-28 at 10 00 57 AM" src="https://github.com/user-attachments/assets/4a121f22-ecf1-4f7a-ba69-f50b638c7947">

2024-08-28 21:55 UTC, merged