tickets/DM-43379: add single-side-of-focus mode to the TIE
lsst-ts/ts_wep_older pull request #242
Opened 2024-07-25 15:30 UTC by jfcrenshaw

2024-07-29 19:45 UTC, jmeyers314 requested changes
Structure all looks good, but I'm not sure I understand the actual algorithmic change here.  I was expecting something like:
```python
  if intra and extra:
    return TIE(intra, extra)
  elif intra:
    tmp_extra = make_image('extra', zks=0)
    return TIE(intra, tmp_extra)*2
  elif extra:
    tmp_intra = make_image('intra', zks=0)
    return TIE(tmp_intra, extra)*2
```

In particular note the factors of 2.  The intuition is that running TIE with an intra-focal donut with Zernikes zk1 and a (possibly optically inconsistent) extra-focal donut with Zernikes zk2 would yield a result of (zk1+zk2)/2.  So if we make a zk2=0 temporary donut and run with that we get (zk1 + 0)/2 out and need to multiply it by 2 to get zk1, which is what we want.  Maybe this is implicitly in the code now, but I couldn't see it.

2024-07-29 19:45 UTC, jmeyers314 commented on python/lsst/ts/wep/estimation/tie.py
> +        Whether to allow Zernike estimation with a single donut. If False,
```suggestion
        Whether to allow Zernike estimation with a single donut. If True,
```

??

2024-07-29 19:45 UTC, jmeyers314 commented on python/lsst/ts/wep/estimation/tie.py
> +        pairs are required. (the default is False)
I'd probably make the baseline the default.  I.e., pairs are required by default.

2024-07-29 19:45 UTC, jmeyers314 commented on python/lsst/ts/wep/estimation/tie.py
> +        pupil.image = gaussian_filter(pupil.mask.astype(float), 2)
Does the size of the gaussian being convolved here matter?  Should we make it a config variable?

2024-07-29 19:45 UTC, jmeyers314 commented on tests/estimation/test_tie.py
> +        diff = np.sqrt(np.sum((zkPair - np.mean([zkIntra, zkExtra], axis=0)) ** 2))
I think we want to test `zkPair` against each of `zkIntra`, `zkExtra` instead of against their mean.

2024-07-31 23:00 UTC, jfcrenshaw commented
> In particular note the factors of 2. The intuition is that running TIE with an intra-focal donut with Zernikes zk1 and a (possibly optically inconsistent) extra-focal donut with Zernikes zk2 would yield a result of (zk1+zk2)/2. So if we make a zk2=0 temporary donut and run with that we get (zk1 + 0)/2 out and need to multiply it by 2 to get zk1, which is what we want. Maybe this is implicitly in the code now, but I couldn't see it.

The current implementation doesn't actually simulate the other donut. Here's why:

The TIE compensates each donut individually. For each, the Zernikes used are the intrinsic Zernikes at the field angle of the donut (which is possibly unique for each donut) and the estimated aberration (which is the same for each donut). If it has the Zernikes totally correct, it should map each donut back to a uniformly illuminated pupil (which is clear because the forward mapping starts with a uniformly illuminated pupil image).

What the current implementation does is assume that the "missing" donut is just a donut that you have perfectly compensated. I.e., it says don't worry about that other donut image at all, just assume its *compensated* image is exactly a uniformly illuminated pupil. Then you can worry about estimating the Zernikes for the other image, using the perfect compensation of the other image. So if I2 is missing, it converges directly to zk1.

Does that make sense?

I did, however, think that maybe using a perfectly compensated pair effectively damps the signal of the remaining aberration. This shouldn't change the final answer, but may slow down convergence, so I tried a version where I multiplied the `zkResid` by 2. However the resulting the Zernikes are effectively the same, and the convergence isn't dramatically different.

Here is an example convergence plot for a single extrafocal donut, comparing implementations with and without the factor of 2:

<img width="671" alt="image" src="https://github.com/user-attachments/assets/1abce00e-8c30-4e40-9f78-2e9a00a718a9">
<img width="671" alt="image" src="https://github.com/user-attachments/assets/edd1cbb1-416c-4d14-806f-d38e2d64cc2f">

It *is* interesting that the max Zernike index updated by each implemenation is largely different (that is what the numbers above the metrics are indicating), however it makes essentially no difference to estimated Zernikes.

2024-08-01 00:01 UTC, jfcrenshaw commented on python/lsst/ts/wep/estimation/tie.py
> +        pupil.image = gaussian_filter(pupil.mask.astype(float), 2)
Earlier tests I ran suggested it didn't but I double checked and I am finding that Zernike 14 is quite sensitive... not sure why, but I just made it configurable for now.

2024-08-06 05:16 UTC, jmeyers314 commented
Thanks for the explanation; yes this all makes sense to me now! :)
I think you're good to go once you fix the merge conflict problems.

2024-08-06 05:16 UTC, jmeyers314 approved these changes

2024-08-06 18:51 UTC, merged