Add comcam full default pipeline
lsst-ts/ts_wep_older pull request #252
Opened 2024-08-14 21:36 UTC by gmegh

2024-08-14 22:04 UTC, jmeyers314 requested changes
Let's change this to something like comCamRapidAnalysisPipeline.yaml

2024-08-14 22:04 UTC, jmeyers314 commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +  cutOutDonutsScienceSensorTask:
Let's use the group pairer. See https://github.com/lsst-ts/ts_wep/blob/develop/tests/testData/pipelineConfigs/testCutoutsFamPipelineGroupPairer.yaml#L6 for an example.

2024-08-14 22:04 UTC, jmeyers314 commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +      python: OverscanCorrectionTask.ConfigClass.fitType = 'MEDIAN'
@mfisherlevine , how do these ISR settings compare to the quicklook pipeline?

2024-08-14 22:06 UTC, jbkalmbach commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +      tables for the AOS visit.
Add blank line at end please.

2024-08-14 22:06 UTC, jbkalmbach commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +description: wep basic processing test pipeline
Can we change the directory name to something more descriptive like "production"?

2024-08-15 11:57 UTC, mfisherlevine commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +      python: OverscanCorrectionTask.ConfigClass.fitType = 'MEDIAN'
Errr, very different indeed, to be honest! quicklook is basically the same as DRP expect with `doBrighterFatter` set to `False` because it's slow, but everything else is super quick and also necessary for pretty much all processing. So the good news is that you'd be getting all of that for free, the bad news is that it's nothing like your current setup...

2024-08-15 16:19 UTC, jmeyers314 commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +      python: OverscanCorrectionTask.ConfigClass.fitType = 'MEDIAN'
Okay, I vote we adopt the quicklook settings.  Guillem, I think you can copy those from https://github.com/lsst/drp_pipe/blob/main/pipelines/_ingredients/DRP-full.yaml#L12 and https://github.com/lsst/drp_pipe/blob/main/pipelines/LSSTComCam/quickLook.yaml#L8.

2024-08-15 16:43 UTC, mfisherlevine commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +      python: OverscanCorrectionTask.ConfigClass.fitType = 'MEDIAN'
I _think_ you should be able to import them actually, rather than copying them. But then maybe this would need to live in that package, not sure. I'd have no problem with that being the case though, personally.

2024-08-16 13:22 UTC, gmegh commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +description: wep basic processing test pipeline
Great suggestion, i really didn't like fullPipelines but ran out of naming imagination

2024-08-16 13:23 UTC, gmegh commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +  cutOutDonutsScienceSensorTask:
Out of curiosity, what does this do, exactly?

2024-08-16 16:32 UTC, jmeyers314 commented on pipelines/fullPipelines/comcamScienceSensorFullPipeline
> +  cutOutDonutsScienceSensorTask:
It controls how exposures are paired up when you run in batch mode (this "pairer" looks at the value of the "group" dimension to find pairs).  It's also required right now if you want to append new aos pipeline results to an existing output collection.

2024-09-04 16:51 UTC, jmeyers314 commented
LGTM.  Thanks Guillem!

2024-09-04 16:51 UTC, jmeyers314 approved these changes

2024-09-24 00:17 UTC, jbkalmbach commented on pipelines/production/comCamRapidAnalysisPipeline.yaml
> +  generateDonutDirectDetectTask:
Sorry, I know this has been hanging around a while but while preparing our notebooks for analysis I've been thinking about`generateDonutFromRefitWcsTask` as our default rather than `generateDonutDirectDetectTask`. What do you think? `fromRefitWcs` might not work if the pointing model is really bad at the start but I think we should talk about trying to use it. Anyway, maybe something to bring up during an AOS meeting.

2024-09-25 02:00 UTC, merged