issue/52/remove_sims_dependencies
lsst-ts/ts_wep_older pull request #54
Opened 2020-12-10 20:09 UTC by jbkalmbach

Still To Do:

- [ ] Run imgCloseLoop.py
- [ ] Run Closed Loop on comcam with Gaia sources
- [ ] Run Closed Loop on lsstFamCam with Gaia sources

2020-12-10 20:10 UTC, jbkalmbach commented
imgCloseLoop.py results look good!

![image](https://user-images.githubusercontent.com/4755090/101824095-96adf400-3ae0-11eb-9e77-a5231f93e756.png)

2020-12-15 19:59 UTC, jbkalmbach commented
Results from running close loop with `lsstFamCam` and 21 stars

![image](https://user-images.githubusercontent.com/4755090/102266124-e15ab200-3ecc-11eb-97e2-e27b2ff59f91.png)

2020-12-15 20:01 UTC, teweitsai commented
What is the boresight and rotation angle for the simulation of `lsstFamCam`?

2020-12-15 20:28 UTC, jbkalmbach commented
Boresight = -0.03, 0.02 and rotation angle = 0.0 just like you showed me here: https://github.com/lsst-ts/ts_phosim/pull/45

I could run adding in rotation angle too? Is there a suggested angle?

2020-12-15 20:43 UTC, jbkalmbach commented
Updating `lsstFamCam` image above to show all CCDs instead of only 9.

![image](https://user-images.githubusercontent.com/4755090/102270668-1cf87a80-3ed3-11eb-98eb-e0c32aff12f0.png)

2020-12-15 20:44 UTC, teweitsai commented
I am thinking just to run 20 or -15 degree or the degree values less than the above. The idea is to test the positive and negative none-zero rotation angle to make sure you can catch them. If the value is too small, there should be no affection. If the value is too big, I guess I never tried that. If the results are not expected, it is good to do the debug at this moment....

2020-12-15 20:45 UTC, jbkalmbach commented
Ok, I will run at 15 degrees and see what happens.

2020-12-22 17:29 UTC, jbkalmbach commented
I checked coordinate locations with a script from `ts_phosim` and put it in a notebook [here](https://gist.github.com/jbkalmbach/ebb53932ae1c2a17d72bd940305e8328).

2020-12-22 22:36 UTC, teweitsai commented on python/lsst/ts/wep/bsc/CameraData.py
> +
This new line is not needed.

2020-12-22 22:36 UTC, teweitsai commented on python/lsst/ts/wep/bsc/CameraData.py
> +        centerCcd : str
This input argument is "optional".

2020-12-22 22:40 UTC, teweitsai commented on python/lsst/ts/wep/bsc/CameraData.py
> +        self._wcs.setObsMetaData(ra, dec, rotSkyPos, self._centerCcd, mjd=mjd)
It might be clear to use:
```
self._wcs.setObsMetaData(ra, dec, rotSkyPos, centerCcd=self._centerCcd, mjd=mjd)
```

2020-12-22 22:43 UTC, teweitsai commented on python/lsst/ts/wep/SourceProcessor.py
This is not needed anymore. Right?

2020-12-22 22:46 UTC, teweitsai commented on python/lsst/ts/wep/SourceProcessor.py
>          return pixelCamX, pixelCamY
You could do the following instead to be more clear:
```
return pixelDmY, pixelDmX
```

2020-12-22 22:51 UTC, teweitsai commented on python/lsst/ts/wep/SourceProcessor.py
>          return pixelDmX, pixelDmY
You could do the following instead to be more clear:
```
return pixelCamY, pixelCamX
```

And please remove the following parts in the previous code in this function:
```
 # Get the CCD dimension
 dimX, dimY = self.sensorDimList[self.sensorName]
```

2020-12-22 23:01 UTC, teweitsai commented on python/lsst/ts/wep/bsc/WcsSol.py
> +            Center Ccd on the camera (the default is "R22_S11")
This input argument should be optional. In addition, you may want to add a "period" in the end of description:

Center Ccd on the camera. (the default is "R22_S11").

2020-12-22 23:01 UTC, teweitsai commented on python/lsst/ts/wep/bsc/WcsSol.py
> +        mjd : float or None
This input argument should be "optional".

2020-12-22 23:07 UTC, teweitsai commented on python/lsst/ts/wep/bsc/WcsSol.py
> +            val2 as a list of values
I think the new line between arguments may not needed. For example:
```
Returns
-------
val1: list
      val1 as a list of values 
val2: list
      val2 as a list of values
```

BTW, you may want to add the "period" for the argument's description.

2020-12-22 23:15 UTC, teweitsai commented on python/lsst/ts/wep/bsc/WcsSol.py
> +        raDecArray = self._raDecFromPixelCoords(xPix, yPix, chipNameList,)
I think it might be better to remove the final comma:
```
raDecArray = self._raDecFromPixelCoords(xPix, yPix, chipNameList)
```

2020-12-22 23:16 UTC, teweitsai commented on python/lsst/ts/wep/bsc/WcsSol.py
> +
This new line is not required.

2020-12-22 23:17 UTC, teweitsai commented on python/lsst/ts/wep/bsc/WcsSol.py
> +
Only needs one new line between the "Parameters" and "Returns" to separate them.

2020-12-22 23:21 UTC, teweitsai commented on python/lsst/ts/wep/bsc/WcsSol.py
> +                # detector then return -9999
Please explain the -9999 in the doc string of function as well.

2020-12-22 23:26 UTC, teweitsai commented on python/lsst/ts/wep/bsc/WcsSol.py
> +            chipNameList = [chipName] * nPts
You could add a `else` case as a default case here to make the code more robust. For this default case, you could raise a `ValueError` because the input argument has the wrong data type that you expected to have.

2020-12-22 23:30 UTC, teweitsai requested changes
There are some comments in the code that you could consider to improve the codes.

2020-12-23 20:24 UTC, jbkalmbach commented on python/lsst/ts/wep/bsc/WcsSol.py
> +            chipNameList = [chipName] * nPts
Added this and added a test for it as well.

2020-12-23 20:25 UTC, jbkalmbach commented on python/lsst/ts/wep/bsc/WcsSol.py
> +                # detector then return -9999
Added into the docstring above.

2020-12-23 21:54 UTC, teweitsai approved these changes
Thanks for the update and improvement of code!

2020-12-23 22:17 UTC, merged