Issue/60/template generator from model
lsst-ts/ts_wep_older pull request #62
Opened 2021-01-28 06:53 UTC by jbkalmbach

2021-01-28 21:29 UTC, teweitsai requested changes
Please base on today's discussion to update the code. Thanks!

2021-02-02 22:27 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateDefault.py
> +        numpy.ndarray [float]
If the return data is a binary image, why the data type is `float` instead of `int`? I thought the convention of binary image should be `int`.

2021-02-02 22:29 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateFactory.py
> +            Algorithm to create the donut templates
Add the period in the end of description.

2021-02-02 22:29 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateFactory.py
> +            Donut template object
Add the period in the end of description.

2021-02-02 22:31 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        camType : enum 'CamType'
This argument is "optional".

2021-02-02 22:31 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        pixelScale : float
This argument is "optional".

2021-02-02 22:32 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        numpy.ndarray [float]
Why the return type is `float` instead of `int` for a binary image?

2021-02-02 22:38 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        sensorXDeg = sensorXPixel * pixelScale / 3600
Maybe put a comment to explain the number of 3600 here?

2021-02-02 22:39 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +            The donut template as a binary image
Add the period in the end of description.

2021-02-02 22:41 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        return templateArray
You can return the value here directly because you explained it in the doc string already:
```
return img.getNonPaddedMask()
```

2021-02-02 22:49 UTC, teweitsai commented on tests/cwfs/test_donutTemplateModel.py
> +        np.testing.assert_array_equal(templateArray, testTemplate)
There is a logic problem here for the test case. It looks like the result of `_createTestTemplate()` is basically a copy of the code of `DonutTemplateModel.makeTemplate()`. Although sometimes I used the similar way to do a quick and dirty test case, I still need to ask myself that do I have any other method to generate the test case or not. Is there any physical property I could use to write the test case to a specific scientific function (not the business logic but science)? Only when I have no good idea, I will use the similar way as what you did here to generate the test case.

2021-02-02 22:50 UTC, teweitsai approved these changes

2021-02-02 22:51 UTC, teweitsai commented
The update looks good to me. Please read my comments before the merge. I have some question for the returned data type of binary image. After the merge, please add the `git tag`. Thanks!

2021-02-03 18:42 UTC, jbkalmbach commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        numpy.ndarray [float]
The output on `CompensableImage.getNonPaddedMask()` becomes `float` after this loop: https://github.com/lsst-ts/ts_wep/blob/master/python/lsst/ts/wep/cwfs/CompensableImage.py#L1422-L1466

2021-02-03 18:43 UTC, jbkalmbach commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        numpy.ndarray [float]
That is why I keep getting floats here. Should I convert my output to `int` before returning it since it is supposed to be a binary image?

2021-02-03 19:29 UTC, jbkalmbach commented on tests/cwfs/test_donutTemplateModel.py
> +        np.testing.assert_array_equal(templateArray, testTemplate)
I changed the tests here. Do you mind taking another look and see if this is better?

2021-02-03 19:29 UTC, jbkalmbach commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        numpy.ndarray [float]
I changed this to return an int since it is supposed to be binary.

2021-02-03 22:10 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        numpy.ndarray [float]
For the link you shared, I think we did try to make the output to be `int` before:
https://github.com/lsst-ts/ts_wep/blob/master/python/lsst/ts/wep/cwfs/CompensableImage.py#L1449-L1453

Can you help to fix the bugs why the `self.cMask` and `self.pMask` are not `int` anymore? If we could fix this, we will not need to do `np.array(img.getNonPaddedMask(), dtype=int)` in `DonutTemplateModel.py`.

Thanks!

2021-02-03 22:13 UTC, teweitsai commented on tests/cwfs/test_donutTemplateModel.py
> +        np.testing.assert_array_equal(templateArray, testTemplate)
I like the updated test case. Thanks!

2021-02-03 22:14 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateDefault.py
> +        numpy.ndarray [float]
I saw you changed this to be `int` in commit: 5aa3d68. Thanks!

2021-02-04 00:54 UTC, jbkalmbach commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        numpy.ndarray [float]
Ok, updated the code in `CompensableImage.py`

2021-02-04 01:03 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplateModel.py
> +        numpy.ndarray [float]
This looks good to me. If all Jenkins test pass, we should be good to merge the code. Thanks!

2021-02-04 18:29 UTC, merged