Issue/61/template generator phosim
lsst-ts/ts_wep_older pull request #64
Opened 2021-02-11 17:30 UTC by jbkalmbach

I wasn't sure the best way to include the templates. Instead of creating all the templates and adding them to the repo I created a script to do this instead. Happy to do it another way if there's a better solution.

2021-02-11 23:43 UTC, teweitsai requested changes
Please update the code based on today's discussion.

2021-02-23 17:55 UTC, teweitsai commented on .gitignore
> +policy/cwfs/donutTemplateData/phosimTemplates/
Please consider to add this directory by using a `.gitignore` file.

2021-02-23 18:31 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplatePhosim.py
> +        templateTrim = templateSize - np.array((imageSize, imageSize))
What will happen if `templateSize < np.array((imageSize, imageSize))`? Do you want to raise an error or do the padding instead?

2021-02-23 18:33 UTC, teweitsai commented on python/lsst/ts/wep/cwfs/DonutTemplatePhosim.py
> +        return templateArray
The updated code here is clear enough that you could do the following instead:
```
return templateArray[leftEdge:rightEdge, topEdge:bottomEdge]
```

2021-02-23 18:40 UTC, teweitsai commented on tests/cwfs/test_donutTemplatePhosim.py
> +            self.defaultPathExists = False
You may not need this if we create the directory in advance by `.gitkeep`. The reason to declare this first before generating the data is to let other users/developers know we might have this directory and data in advance to avoid any surprise when he/she runs the code.

2021-02-23 18:47 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +from lsst.ts.wep.cwfs.CentroidRandomWalk import CentroidRandomWalk
Please import the `CentroidFindFactory` and use the `CentroidFindFactory.createCentroidFind()` instead to get the `CentroidRandomWalk` instance. Since we are using the factory pattern now, it is easier to do the future's maintenance.

2021-02-23 18:52 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        self.repoDir = os.path.join(self.tempWorkPath, "input")
Please add the comment for each class's attributes (`self.policyDir, self.repoDir, etc.`) to explain the details. The developers are used to read the `__init__()` to know what attributes this class has. Sometimes, it might be hard to guess the meaning of a specific attribute just base on the attribute's name.

2021-02-23 18:59 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +            self.templateDestDir = templateDestDir
I have the question of the design decision to let the user can assign a specific directory of templates. Does this mean we may also need to add the related parameter in `default.yaml` to tell the WEP to look for that directory in the file system? If you have the default directory: `policy/cwfs/donutTemplateData/phosimTemplates` already, why not just use it? It looks like you have put that directory into the `.gitignore` and this means the other users will not commit the local template files to the upstream by the accident. I felt this might decrease the complexity. What do you think?

2021-02-23 19:02 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +            sensorNameList = detectorStr.split(" ")
People use the empty lines to improve the readability. But too many empty lines might hurt the readability as well.

2021-02-23 19:05 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +                sensorData = yaml.load(f, Loader=yaml.FullLoader)
I prefer to use the `ParamReader` to get the details in the `yaml` file. But if you really want to use the `yaml` library directly, please consider to use the `yaml.safe_load()` instead of `yaml.load()`.

2021-02-23 19:12 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +            detectorStrFlats += f"{sensorName} "
You could consider to use the `join()` to simplify the code:
https://www.geeksforgeeks.org/python-program-to-convert-a-list-to-string/

2021-02-23 19:17 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        runPhosimArgs += f"-i lsst "
Will we generate the "comcam" in the future?

2021-02-23 19:20 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +
This new line is not needed.

2021-02-23 19:20 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +
This new line is not needed.

2021-02-23 19:22 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +
This new line is not needed.

2021-02-23 19:22 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +
This new line is not needed.

2021-02-23 19:22 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +
This new line is not needed.

2021-02-23 19:22 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +
This new line is not needed.

2021-02-23 19:22 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +
This new line is not needed.

2021-02-23 19:24 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        centroidRW = CentroidRandomWalk()
Please use the factory method to get this instance for the future's maintanance.

2021-02-23 19:32 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +                testHdu = fits.open(os.path.join(sensorPath, templateFile))
If you just want to get the data in fits file, you could use the `fits.getdata()` instead. You could also consider to use the `cwfs/Image.py` to get the data. I tried to restrict the use of `fits` library in that `Image` class only if people only cares about the image data instead of the header information.

2021-02-23 19:37 UTC, teweitsai commented on tests/test_createPhosimDonutTemplates.py
> +class TestCreatePhosimDonutTemplates(unittest.TestCase):
I think you could add other test cases such as the remove of temporary directories as well. It is good to have at least a test case for each public function if it is possible.

2021-02-23 19:41 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        runProgram("ingestCalibs.py", argstring=argString)
Why you call the `ingestCalibs.py` here instead of using the `CamDataCollector`? I ask this because you used the `CamIsrWrapper` in `runISR()`.

2021-02-23 19:43 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        runProgram("ingestImages.py", argstring=f"{self.repoDir} {ampImg}")
Why you call the `ingestImages.py` here instead of using the `CamDataCollector`? I ask this because you used the `CamIsrWrapper` in `runISR()`.

2021-02-23 19:46 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        cmdString = f"echo lsst.obs.lsst.phosim.PhosimMapper > {self.tempWorkPath}/input/_mapper"
The `CamDataCollector` has the `genPhoSimMapper()` to do this. I think the main question is that after you update the `ts_wep` to use the gen3 butler, should we keep these wrapper classes or not.

2021-02-23 20:37 UTC, teweitsai approved these changes

2021-02-23 20:38 UTC, teweitsai commented
The update looks good to me. I only have some suggestions/questions maybe you could consider.

2021-02-23 23:06 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        runPhosimArgs += f"-i lsst "
Maybe we do not need this because comcam is similar to the central raft of lsst.

2021-03-01 19:26 UTC, jbkalmbach commented on tests/test_createPhosimDonutTemplates.py
> +    def tearDown(self):
@teweitsai I am unsure on the best practice to design the `tearDown` when not all the methods create data that needs to be removed. 

The first `try...except` is here because only the `testCutOutTemplatesAndSave` test creates this file. 

The second `try...except` is here because I want to test the creation and clean up of the directories but if that test fails I need to be able to clean that directory still. But if it succeeds then there is nothing to clean up.

2021-03-02 01:55 UTC, teweitsai commented
I think the commit: 333f899 is a good update! Thanks for the update!

2021-03-02 18:34 UTC, merged