tickets/DM-28330: Update to lsstCam mapper
lsst-ts/ts_wep_older pull request #72
Opened 2021-03-10 20:51 UTC by suberlak

Updates needed to conform to the new file format from [DM-28556](https://jira.lsstcorp.org/browse/DM-28556) (`phosim_utils`), and the new  geometry, gain,  read noise  etc. for `lsstCam` in `focalplanelayout.txt` following [DM-28557](https://jira.lsstcorp.org/browse/DM-28557) (`phosim_syseng4`) . This makes ts_wep compatible with the updated gain / read noise values in `obs_lsst` for `lsstCam`  from [DM-28553](https://jira.lsstcorp.org/browse/DM-28553).

2021-03-10 23:55 UTC, jbkalmbach reviewed
The phosim template changes look fine to me. I'll let Te-Wei comment on the rest. See comments about string formatting.

2021-03-10 23:56 UTC, teweitsai requested changes
Please clean up and organize the git history before the review (make use of `git rebase -i [commit]`). The value of "Files changed" showed the infinity and the error message is: **Sorry, this diff is taking too long to generate**.

2021-03-10 23:57 UTC, jbkalmbach commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        runPhosimArgs += f'{"-i lsst "}'
Does it work if you just make this not an f string instead of having a string inside a string?

2021-03-10 23:57 UTC, jbkalmbach commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        print(f'{"Repackaging phosim output"}')
Same comment about strings above.

2021-03-11 01:39 UTC, suberlak commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        runPhosimArgs += f'{"-i lsst "}'
It probably would  - flake8 complained of `f"-i lsst "`, I can change that to `"-i lsst "` I think .

2021-03-11 01:49 UTC, suberlak commented
Cleaned up as requested, rebasing, resetting, and  organizing all added / deleted test files as a single commit. Then each python file follows as a single commit.

2021-03-11 01:51 UTC, suberlak commented
In "files changed" you can select a range of which commits to show, or see them one by one.

2021-03-11 01:52 UTC, suberlak commented
"Files changed " will show infinity regardless because of the file size.

2021-03-11 15:11 UTC, teweitsai commented on python/lsst/ts/wep/CamDataCollector.py
> +    def genLsstCamMapper(self):
Please remove the `genPhoSimMapper()` because we will not use it anymore. In addition, there is no backward compatibility anymore.

2021-03-11 15:14 UTC, teweitsai commented on python/lsst/ts/wep/CamIsrWrapper.py
> +        doCrosstalk=False,
Please add this new optional argument in the doc string.

2021-03-11 15:16 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        runPhosimArgs += f'{"-i lsst "}'
Please do `runPhosimArgs += "-i lsst "` instead to simply it.

2021-03-11 15:17 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        runPhosimArgs += f'{"-e 1 "}'
Please simplify with `runPhosimArgs += "-e 1 "`.

2021-03-11 15:18 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +        print(f'{"Repackaging phosim output"}')
Please simplify with `print("Repackaging phosim output")`.

2021-03-11 15:20 UTC, teweitsai commented on python/lsst/ts/wep/CreatePhosimDonutTemplates.py
> +
You do not need this new line.

2021-03-11 15:22 UTC, teweitsai commented on python/lsst/ts/wep/Utility.py
> +    list
Is the output `list [str]`? Please update the doc string to give the data type of list elements.

2021-03-11 15:24 UTC, teweitsai commented on python/lsst/ts/wep/ctrlIntf/WEPCalculation.py
>                  dataCollector.genPhoSimMapper()
Please remove the "phosim" mapper because we will not use it anymore. In addition, there is no backward compatibility. I think the next mapper to support is only the comcam.

2021-03-11 15:26 UTC, teweitsai commented on python/lsst/ts/wep/ctrlIntf/WEPCalculation.py
> +                rawImgFiles = " "
Why is it `rawImgFiles = " "` instead of `rawImgFiles = ""`?

2021-03-11 15:34 UTC, teweitsai commented on tests/test_wepControllerMonolithic.py
> +            rawImgFiles = " "
Why is it `rawImgFiles = " "` instead of `rawImgFiles = ""`?

2021-03-11 15:36 UTC, teweitsai commented on python/lsst/ts/wep/Utility.py
> +def getAmpImagesFromDir(rawExpDir):
Please add the related unit test at `test_utility.py`.

2021-03-11 15:36 UTC, teweitsai commented
Please update the `doc/versionHistory.rst`. Thanks!

2021-03-11 15:42 UTC, teweitsai approved these changes

2021-03-11 20:12 UTC, merged