Tickets/dm 29688
lsst-ts/ts_wep_older pull request #78
Opened 2021-04-13 05:24 UTC by jbkalmbach

Initial code to create a source catalog from pointing information using Gen3 middleware.

There are a couple notes in the code about related issues that will require us to update the code when they are merged.

2021-04-13 14:51 UTC, teweitsai commented
Please do the rebase after @tribeiro merges the `tickets/DM-29687`. The docker image of `Jenkinsfile` is changed to `lsstts/develop-env`. I would like to check this PR can pass under this docker image. Thanks!

2021-04-13 22:05 UTC, teweitsai commented on tests/testData/gen3TestRepo/convertRefCat.cfg
> +config.refCats = ["cal_ref_cat"]
Please add a new line after this. In addition, please help to add the comments to explain the details of this file and the setting used.

2021-04-13 22:08 UTC, teweitsai commented on tests/testData/gen3TestRepo/refCat.cfg
> +config.mag_err_column_map={'g':'g_err'}
Please add the new line in the end of file. In addition, is it possible to do something like this for the readability?
```
config.mag_err_column_map = {'g':'g_err'}
```

2021-04-13 22:09 UTC, teweitsai commented on tests/testData/gen3TestRepo/refCat.cfg
> +# config.dataset_config.ref_dataset_name='test_refcat'
Do you need this and what is it?
```
# config.dataset_config.ref_dataset_name='test_refcat'
```

2021-04-13 22:10 UTC, teweitsai commented on tests/testData/gen3TestRepo/refCat.cfg
> +# photometric information.  At least one entry is required.
# The values in the reference catalog are assumed to be in AB magnitudes.
# List of column names to use for photometric information.
# At least one entry is required.

2021-04-13 22:11 UTC, teweitsai commented on tests/testData/phosimOutput/realComCam/skyComCamInfoRefCatalog.txt
> +id,ra,dec,g,g_err
Please add the comments to explain the details of this test file.

2021-04-13 22:12 UTC, teweitsai commented on tests/test_generateDonutCatalogOnlineTask.py
> +#
Do you need this first line?
```
#
```

2021-04-13 22:13 UTC, tribeiro commented
I think you need to reformat the code with [black](https://black.readthedocs.io/en/stable/). We adopted black 20 now.

2021-04-13 22:14 UTC, teweitsai commented on tests/test_generateDonutCatalogOnlineTask.py
> +# LSST Data Management System
```
# This file is part of ts_wep.
#
# Developed for the LSST Telescope and Site Systems.
```

It might be better to be consistent for the license declaration. If you want to change it, please change all `python` files.

2021-04-13 22:20 UTC, teweitsai commented on tests/testData/gen3TestRepo/butler.yaml
> +    opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
Please add the comments to explain each items in this `yaml` file.

2021-04-13 22:21 UTC, teweitsai commented on tests/testData/createGen3TestRepo.sh
> +# Convert to Gen 3 (currently only way to get Gen3 ref cat)
Please add a new/empty line before this for the readability.

2021-04-13 22:22 UTC, teweitsai commented on tests/testData/createGen3TestRepo.sh
> +# Ingest Raws
Please add a new/empty line before this for the readability.

2021-04-13 22:22 UTC, teweitsai commented on tests/testData/createGen3TestRepo.sh
> +# Make Gen 2 Repo for ref cat
reference catalog?

2021-04-13 22:23 UTC, teweitsai commented on tests/testData/createGen3TestRepo.sh
> +rm -r gen2TestRepo
Please add a new line after this.

2021-04-13 22:24 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +# Copyright 2008-2017 AURA/LSST.
```
# This file is part of ts_wep.
#
# Developed for the LSST Telescope and Site Systems.
```

It might be better to be consistent for the license declaration. If you want to change it, please change all `python` files.

2021-04-13 23:25 UTC, jbkalmbach commented on tests/testData/gen3TestRepo/butler.yaml
> +    opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
This is the file created automatically by the butler when making the repository. I didn't create these settings so I'm not sure what they all mean.

2021-04-13 23:49 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +class GenerateDonutCatalogOnlineTaskConnections(
Please add the doc string for this class. In addition, please update the `doc/wepClass.uml` and `doc/content.rst` as well. BTW, I prefer each class has its own python file. This is easier to maintain and know which python file to update the code.

2021-04-13 23:50 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +class GenerateDonutCatalogOnlineTaskConfig(
Please add the doc string for this class. In addition, please update the `doc/wepClass.uml` and `doc/content.rst` as well. BTW, I prefer each class has its own python file. This is easier to maintain and know which python file to update the code.

2021-04-13 23:52 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +class GenerateDonutCatalogOnlineTask(pipeBase.PipelineTask):
Please update the `doc/wepClass.uml` and `doc/content.rst` as well. BTW, I prefer each class has its own python file. This is easier to maintain and know which python file to update the code. Or you could have a new module in `ts_wep` to put the pipeline tasks. This might be easier to maintain.

2021-04-13 23:54 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        self.cameraName = self.config.cameraName
Please add the comments to explain each attributes.

2021-04-13 23:59 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        os.environ["NUMEXPR_MAX_THREADS"] = "1"
Please consider to put this into the configuration file as such the `policy/default.yaml`. You could see the `numOfProc` is there already. If the pipeline task is based on the `thread`, maybe rename the `numOfProc` to `numOfThread` and modify the related description.

PS. In Linux, there should be no much difference between thread and processor in the internal realization.

2021-04-13 23:59 UTC, jbkalmbach commented on tests/testData/gen3TestRepo/refCat.cfg
> +# photometric information.  At least one entry is required.
AB magnitude is just the astronomical magnitude system expected by the LSST DM code.

https://en.wikipedia.org/wiki/AB_magnitude

2021-04-14 00:00 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        """
Please provide the doc string of input argument: `resultsDataFrame`. BTW, I felt the doc string you put is more like the comments of this function instead of its purpose. Please consider to rewrite it.

2021-04-14 00:01 UTC, jbkalmbach commented on tests/testData/phosimOutput/realComCam/skyComCamInfoRefCatalog.txt
> +id,ra,dec,g,g_err
Is there someplace else I can put the explanation for this file? If I add the comments here the file does not get ingested by the Butler properly.

2021-04-14 00:02 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +    ) -> pipeBase.Struct:
I think this function is inherit from the parent and you do not put the doc string. Is this correct?

2021-04-14 00:05 UTC, jbkalmbach commented
> I think you need to reformat the code with [black](https://black.readthedocs.io/en/stable/). We adopted black 20 now.

I did using version `20.8b1`. What files look like they were missed?

2021-04-14 00:07 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        if self.cameraName == "lsstCam":
I think it is better to use the `Utility.CamType` and the user could put this in the runtime or read from the configuration file (`camMapper` in `policy/default.yaml`). You could raise the error if that camera is not supported yet. It is better to not hard-coded the camera here.

2021-04-14 00:07 UTC, jbkalmbach commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +    ) -> pipeBase.Struct:
Yes, that is correct.

2021-04-14 00:09 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        for detector in lsst_cam:
We do not want to hard-coded the camera here (`lsst_cam`). You could do the following as an example:
```
camera = obs_lsst.LsstCam.getCamera()
for detector in camera:
```

2021-04-14 00:13 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +            )
I felt the code here is a duplication of `WcsSol` (you have `90.0` in both side). I prefer you use the `WcsSol` instead. Then, when you need to fix this, you only need to fix one part of code. The idea is to reduce the duplication as more as possible.

2021-04-14 00:15 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        return pipeBase.Struct(donutCatalog=finalSources)
It might be good to explain the output if you do not have the related doc string.

2021-04-14 00:16 UTC, teweitsai requested changes
1. Please update the `doc/versionHistory.rst`.
2. Is it possible to create the following file in the test instead of putting into the repo?
`tests/testData/gen3TestRepo/gen3.sqlite3`
3. Please fix the warnings in Jenkins test.

2021-04-14 00:20 UTC, teweitsai commented on tests/testData/gen3TestRepo/refCat.cfg
> +# photometric information.  At least one entry is required.
Is it normal to write the abbreviation? I prefer the full name actually because the developers/maintainers may not be in this field (at least, I am not).

2021-04-14 00:22 UTC, teweitsai commented on tests/testData/phosimOutput/realComCam/skyComCamInfoRefCatalog.txt
> +id,ra,dec,g,g_err
Do you mean you could not do something like this?
```
# this is the explanation
id,ra,dec,g,g_err
```

If this is the case, maybe explain it a little bit in `README.md`.

2021-04-14 00:23 UTC, teweitsai commented on tests/testData/gen3TestRepo/butler.yaml
> +    opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
Can you help to explain this part in `README.md`?

2021-04-14 22:07 UTC, jbkalmbach commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        os.environ["NUMEXPR_MAX_THREADS"] = "1"
This is only temporary until that issue gets closed. This number should always be 1 inside this pipe task or there will be problems with the multiprocessing in the quantum graph structure.

2021-04-15 00:37 UTC, jbkalmbach commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        if self.cameraName == "lsstCam":
I would rather have it come from the `GenerateDonutCatalogOnlineTaskConfig` class so we can keep everything for this Task in one place. I think this will be especially useful when running as a pipeline task since the configurations can all be specified in the pipeline `yaml` file used to specify the tasks and configurations in a pipeline.

2021-04-15 01:02 UTC, jbkalmbach commented on tests/testData/gen3TestRepo/refCat.cfg
> +# photometric information.  At least one entry is required.
It's always just called the AB magnitude system. I think it's not even an abbreviation but historically short for "absolute" something...calibration maybe...but I don't actually know.

2021-04-15 04:12 UTC, teweitsai commented on python/lsst/ts/wep/GenerateDonutCatalogOnlineTask.py
> +        if self.cameraName == "lsstCam":
Yes. I think you are right. This comes from `self.cameraName = self.config.cameraName`. Thanks!

2021-04-15 21:41 UTC, jbkalmbach commented
> 1. Please update the `doc/versionHistory.rst`.
> 2. Is it possible to create the following file in the test instead of putting into the repo?
>    `tests/testData/gen3TestRepo/gen3.sqlite3`
> 3. Please fix the warnings in Jenkins test.

I added information for `gen3.sqlite3` in the documentation but it does need to be there for the Gen 3 Test Repo to work.

I don't think any of the warning in the Jenkins test are from the code I added. I think the `np.bool` warnings are because the version of `skimage` in the stack needs to be updated. Perhaps we need a new issue+PR to take care of the other ones?

2021-04-15 23:22 UTC, teweitsai commented on README.md
> +files `tests/testData/createGen3TestRepo.sh`. This script performs the following steps to create the Gen 3 repository:
Please put each sentence as a new line for the benefit of `git diff` in future:

In the folder `tests/testData/` there is a test repository for tasks that run with the Gen 3 DM middleware.
This repository is the folder `tests/testData/gen3TestRepo` and was built using the files `tests/testData/createGen3TestRepo.sh`.
This script performs the following steps to create the Gen 3 repository:

2021-04-15 23:25 UTC, teweitsai commented on README.md
> +  4. Clean up the original Gen 2 repository.
Please put each sentence as a new line for the benefit of `git diff` in future. You could do some experiments and check the format will keep the same even the new line is used. In addition, you may not need the space before each point (1, 2, 3, 4).

2021-04-15 23:30 UTC, teweitsai commented on python/lsst/ts/wep/task/GenerateDonutCatalogOnlineTask.py
> +    _DefaultName = "GenerateDonutCatalogOnlineTask"
Does the `_DefaultName` need to be the same as class name? If this is the case, should we comment this or find a way to get this attribute's value programmatically?

2021-04-15 23:31 UTC, teweitsai commented on doc/uml/taskClass.uml
> +GenerateDonutCatalogOnlineTaskConfig --* GenerateDonutCatalogOnlineTask
This should be:
```
GenerateDonutCatalogOnlineTaskConfig *-- GenerateDonutCatalogOnlineTaskConnections 
GenerateDonutCatalogOnlineTask *-- GenerateDonutCatalogOnlineTaskConfig
```
Do you see the difference in the generate figure?

2021-04-15 23:32 UTC, teweitsai commented on doc/uml/taskClass.uml
> +@enduml
Please add a new line after this.

2021-04-15 23:32 UTC, teweitsai approved these changes
This PR looks good to me. I have some comments that you could consider before the merge. Thanks!

2021-04-16 19:44 UTC, jbkalmbach commented on python/lsst/ts/wep/task/GenerateDonutCatalogOnlineTask.py
> +    _DefaultName = "GenerateDonutCatalogOnlineTask"
It doesn't need to be the same as the class name but I think you need to give it a descriptive name for the pipeline maybe. All the other pipeline tasks I've been using as a template have something similar to the class name here.

2021-04-16 20:40 UTC, merged